"use client";
import { useEffect,useMemo,useState } from "react";
import { Archive, BrainCircuit, BookOpen, CheckCircle2, ClipboardList, FileText, Lightbulb, Send, Sparkles } from "lucide-react";
import Shell from "../../../components/dashboard/Shell";
import { askAI,conversation,conversations,archiveConversation } from "../../../lib/api/ai";

const modes=[
 {key:"tutor",label:"Learn with a tutor",description:"Understand concepts through explanations and examples.",icon:BookOpen,placeholder:"What concept would you like to understand?"},
 {key:"coach",label:"Learning coach",description:"Turn a goal into a realistic study plan.",icon:Lightbulb,placeholder:"What are you trying to learn or achieve?"},
 {key:"practice",label:"Practice generator",description:"Create exercises and get hints before solutions.",icon:ClipboardList,placeholder:"What topic and difficulty should we practise?"},
 {key:"project",label:"Project guidance",description:"Plan, debug and improve practical work.",icon:BrainCircuit,placeholder:"Describe your project and where you are stuck."},
 {key:"summarise",label:"Lesson summariser",description:"Summarise lesson material you provide.",icon:FileText,placeholder:"Paste lesson text or notes, then tell me the summary format you need."},
];
export default function AIPage(){
 const [mode,setMode]=useState("tutor"),[q,setQ]=useState(""),[messages,setMessages]=useState<any[]>([]),[cid,setCid]=useState<string>(),[busy,setBusy]=useState(false),[err,setErr]=useState(""),[history,setHistory]=useState<any[]>([]);
 const selected=useMemo(()=>modes.find(m=>m.key===mode)||modes[0],[mode]);
 useEffect(()=>{const context=sessionStorage.getItem("learnora_ai_context");if(context){setQ(context);sessionStorage.removeItem("learnora_ai_context");}conversations().then(async x=>{const rows=x.conversations||[];setHistory(rows);const c=rows.find((item:any)=>item.feature===mode);if(c){setCid(c.id);const y=await conversation(c.id);setMessages(y.messages||[])}}).catch(()=>{});},[]);
 async function changeMode(key:string){setMode(key);setMessages([]);setCid(undefined);setErr("");try{const rows=(await conversations()).conversations||[];setHistory(rows);const c=rows.find((item:any)=>item.feature===key);if(c){setCid(c.id);const y=await conversation(c.id);setMessages(y.messages||[])}}catch{}}
 async function ask(){if(!q.trim()||busy)return;const text=q.trim();setQ("");setErr("");setMessages(m=>[...m,{role:"user",content:text}]);setBusy(true);try{const r=await askAI(text,mode,cid);setCid(r.conversation_id);setMessages(m=>[...m,{role:"assistant",content:r.content||"No response returned."}]);conversations().then(x=>setHistory(x.conversations||[])).catch(()=>{});}catch(e:any){setErr(e.message||"The AI response could not be generated.");setMessages(m=>[...m,{role:"assistant",content:"I could not complete that request. Please review the message below and try again when the service is available."}]);}finally{setBusy(false)}}
 async function archive(){if(!cid)return;try{await archiveConversation(cid);setCid(undefined);setMessages([]);setHistory(h=>h.filter(x=>x.id!==cid));}catch(e:any){setErr(e.message||"Conversation could not be archived.")}}
 return <Shell active="ai"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="text-xs font-bold uppercase tracking-[.2em] gold">Learnora AI</p><h1 className="mt-3 font-display text-4xl sm:text-5xl">A little help for the next step.</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-slate-400">Choose the kind of support you need. AI can help you think and practise; it does not replace an instructor's review or verify a skill by itself.</p></div><div className="flex items-center gap-2 rounded-xl border border-white/10 bg-[#0e1319] px-4 py-3 text-xs text-slate-500"><Sparkles size={15} className="gold"/> Conversations are saved to your account</div></div>
 <div className="mt-8 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{modes.map(({key,label,description,icon:Icon})=><button key={key} onClick={()=>changeMode(key)} aria-pressed={mode===key} className={"rounded-2xl border p-4 text-left transition "+(mode===key?"border-[#d7ad35]/40 bg-[#d7ad35]/[.08]":"border-white/[.08] bg-[#0e1319] hover:border-white/20")}><Icon className={mode===key?"gold":"text-slate-500"} size={20}/><p className="mt-4 text-sm font-semibold">{label}</p><p className="mt-2 text-xs leading-5 text-slate-500">{description}</p></button>)}</div>
 <section className="mt-6 overflow-hidden rounded-3xl border border-white/[.07] bg-[#0e1319]"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-white/[.07] p-5"><div><h2 className="font-semibold">{selected.label}</h2><p className="mt-1 text-xs text-slate-500">{selected.description}</p></div><div className="flex items-center gap-3">{history.length>0&&<span className="text-xs text-slate-600">{history.filter(x=>x.feature===mode).length} saved in this mode</span>}{cid&&<button onClick={archive} className="inline-flex items-center gap-2 text-xs text-slate-500 hover:text-white"><Archive size={14}/> Archive</button>}</div></div>
 <div aria-live="polite" className="min-h-[340px] max-h-[560px] space-y-4 overflow-y-auto p-5 sm:p-7">{messages.length?messages.map((m,i)=><div key={m.id||i} className={"max-w-3xl whitespace-pre-wrap rounded-2xl p-4 text-sm leading-7 "+(m.role==="user"?"ml-auto border border-[#d7ad35]/20 bg-[#d7ad35]/[.08] text-[#f2d477]":"border border-white/[.06] bg-black/20 text-slate-300")}>{m.content}</div>):<div className="mx-auto flex max-w-md flex-col items-center py-20 text-center"><selected.icon size={28} className="gold"/><p className="mt-5 font-semibold">{selected.label}</p><p className="mt-2 text-sm leading-6 text-slate-500">{mode==="summarise"?"Paste the lesson text you want summarised. The assistant should only summarise material you provide.":"Tell Learnora what you are working on. You can ask follow-up questions as you go."}</p></div>}</div>
 <form onSubmit={e=>{e.preventDefault();ask()}} className="border-t border-white/[.07] p-4 sm:p-5"><label htmlFor="ai-prompt" className="sr-only">Message Learnora AI</label><div className="flex items-end gap-3"><textarea id="ai-prompt" value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();ask()}}} rows={3} className="min-h-20 flex-1 resize-y rounded-xl border border-white/10 bg-black/20 p-4 text-sm outline-none focus:border-[#d7ad35]/40" placeholder={selected.placeholder}/><button type="submit" disabled={busy||!q.trim()} className="inline-flex h-12 items-center gap-2 rounded-xl bg-[#d7ad35] px-4 font-semibold text-black disabled:opacity-50">{busy?"Working…":<><Send size={15}/>Send</>}</button></div><p className="mt-3 text-xs text-slate-600">Avoid sharing passwords, private personal information or confidential organisational data.</p>{err&&<p role="alert" className="mt-3 text-sm text-red-300">{err}</p>}</form></section>
 <div className="mt-5 flex items-start gap-3 rounded-xl border border-emerald-400/10 bg-emerald-400/[.03] p-4"><CheckCircle2 className="mt-0.5 shrink-0 text-emerald-300" size={17}/><p className="text-xs leading-6 text-slate-500">Use AI feedback as guidance. Skills, assessments and project evidence should be reviewed against appropriate criteria before being represented as verified.</p></div>
 </Shell>;
}