"use client";
import{useEffect,useMemo,useRef,useState}from"react";
import Shell from"../../../../components/dashboard/Shell";
import EmptyState from"../../../../components/feedback/EmptyState";
import{request}from"../../../../lib/api/client";
import{FileText,Save,Sparkles,CheckCircle2}from"lucide-react";
export default function LearningPlayer({params}:{params:{courseId:string}}){
 const[d,setD]=useState<any>(),[err,setErr]=useState(""),[media,setMedia]=useState<any>({videos:[],resources:[]}),[current,setCurrent]=useState<any>(null),[notes,setNotes]=useState(""),[noteBusy,setNoteBusy]=useState(false),[noteState,setNoteState]=useState(""),[noteError,setNoteError]=useState("");
 const lastSaved=useRef(0);
 useEffect(()=>{request<any>("/progress/courses/"+encodeURIComponent(params.courseId)).then(x=>setD(x.progress)).catch(x=>setErr(x.message||"Course progress could not be loaded."))},[params.courseId]);
 const lessons=useMemo(()=>d?.modules?.flatMap((m:any)=>m.lessons||[])||[],[d]);
 useEffect(()=>{if(!current&&lessons.length)setCurrent(lessons.find((l:any)=>!l.progress?.completed)||lessons[0])},[lessons,current]);
 useEffect(()=>{if(!current)return;lastSaved.current=0;setMedia({videos:[],resources:[]});setNotes("");setNoteState("");setNoteError("");request<any>("/progress/lessons/"+encodeURIComponent(current.id)+"/media").then(setMedia).catch(x=>setErr(x.message||"Lesson media could not be loaded."));request<any>("/progress/lessons/"+encodeURIComponent(current.id)+"/notes").then(x=>setNotes(x.note?.content||"")).catch(x=>setNoteError(x.message||"Lesson notes are not available for this lesson."));},[current?.id]);
 const saveProgress=(percent:number,position:number,completed=false)=>{if(!current)return;request<any>("/progress/lessons/"+encodeURIComponent(current.id),{method:"PUT",body:JSON.stringify({progress_percent:Math.max(0,Math.min(100,Math.round(percent))),completed,last_position_seconds:Math.max(0,Math.round(position))})}).then(x=>setD(x.course_progress)).catch(x=>setErr(x.message||"Progress could not be saved."));};
 async function saveNotes(){if(!current)return;setNoteBusy(true);setNoteError("");setNoteState("");try{await request("/progress/lessons/"+encodeURIComponent(current.id)+"/notes",{method:"PUT",body:JSON.stringify({content:notes})});setNoteState("Notes saved to your account.");}catch(e:any){setNoteError(e.message||"Notes could not be saved.");}finally{setNoteBusy(false)}}
 function askAI(){const context="Course: "+(d.course?.title||d.title||"Current course")+"\nLesson: "+(current?.title||"Current lesson")+"\n\n"+((current?.content||"No lesson text is available. Use the lesson title and my question as context.").slice(0,8000))+"\n\nPlease help me understand this lesson. Explain the key ideas and give a practical example.";sessionStorage.setItem("learnora_ai_context",context);location.href="/dashboard/ai";}
 if(err&&!d)return <Shell active="learning"><EmptyState title="Learning unavailable" message={err}/></Shell>;
 if(!d)return <Shell active="learning"><p className="text-slate-500">Loading your course…</p></Shell>;
 const video=media.videos?.[0];
 return <Shell active="learning"><div className="grid gap-6 lg:grid-cols-[280px_1fr]">
 <aside className="h-fit rounded-2xl border border-white/[.07] bg-[#0e1319] p-4"><p className="mb-2 text-xs uppercase tracking-[.2em] gold">Course progress</p><h2 className="text-lg font-semibold">{d.course?.title||d.title||"Your course"}</h2><div className="mb-5 mt-4 text-3xl font-semibold">{d.progress_percent||0}%</div><div className="mb-4 h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-[#d7ad35]" style={{width:Math.max(0,Math.min(100,d.progress_percent||0))+"%"}}/></div>{d.modules?.map((m:any)=><div key={m.id} className="mb-4"><p className="px-2 pb-2 text-[10px] uppercase tracking-[.14em] text-slate-600">{m.title}</p>{(m.lessons||[]).map((l:any)=><button key={l.id} onClick={()=>setCurrent(l)} className={"mb-1 w-full rounded-xl p-3 text-left text-sm "+(current?.id===l.id?"bg-[#d7ad35]/10 text-[#f2d477]":"text-slate-400 hover:bg-white/[.03]")}>{l.title}<span className="ml-2 text-xs text-slate-700">{l.progress?.completed?"✓":""}</span></button>)}</div>)}</aside>
 <section className="rounded-3xl border border-white/[.07] bg-[#0e1319] p-5 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[.2em] text-slate-600">Lesson {current?.lesson_type?"· "+current.lesson_type:""}</p><h1 className="mt-2 font-display text-4xl">{current?.title||"Select a lesson"}</h1></div>{current&&<button onClick={askAI} className="inline-flex items-center gap-2 rounded-xl border border-[#d7ad35]/20 bg-[#d7ad35]/[.05] px-4 py-3 text-sm font-semibold gold"><Sparkles size={15}/> Ask AI about this lesson</button>}</div>
 {video?.signed_url?<video key={video.id} className="mt-8 w-full rounded-2xl bg-black" controls preload="metadata" src={video.signed_url} onTimeUpdate={e=>{const el=e.currentTarget;if(el.currentTime-lastSaved.current>=15){lastSaved.current=el.currentTime;saveProgress(el.duration?el.currentTime/el.duration*100:0,el.currentTime)}}} onEnded={e=>saveProgress(100,e.currentTarget.currentTime,true)}/>:video?.provider==="youtube"&&video?.external_video_id?<iframe title={current?.title||"Lesson video"} className="mt-8 aspect-video w-full rounded-2xl" src={"https://www.youtube.com/embed/"+encodeURIComponent(video.external_video_id)} allowFullScreen/>:video?.provider==="vimeo"&&video?.external_video_id?<iframe title={current?.title||"Lesson video"} className="mt-8 aspect-video w-full rounded-2xl" src={"https://player.vimeo.com/video/"+encodeURIComponent(video.external_video_id)} allowFullScreen/>:<div className="mt-8 rounded-2xl bg-black/20 p-6 text-sm text-slate-500">{current?.content?"Text-based lesson material":"This lesson does not have video or text content yet."}</div>}
 {current?.content&&<article className="mt-6 whitespace-pre-wrap text-sm leading-8 text-slate-300">{current.content}</article>}
 {media.resources?.length>0&&<div className="mt-7"><h2 className="font-semibold">Lesson resources</h2><div className="mt-3 grid gap-2">{media.resources.map((r:any)=><a key={r.id} href={r.signed_url||r.external_url||"#"} target="_blank" rel="noreferrer" className="rounded-xl border border-white/[.07] p-3 text-sm text-slate-400 hover:text-slate-200">{r.title}</a>)}</div></div>}
 {current&&<div className="mt-8 rounded-2xl border border-white/[.07] bg-black/15 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><FileText className="gold" size={18}/><h2 className="font-semibold">My lesson notes</h2></div>{noteState&&<span className="inline-flex items-center gap-1 text-xs text-emerald-200"><CheckCircle2 size={13}/>{noteState}</span>}</div><p className="mt-2 text-xs leading-5 text-slate-500">Notes are private to your account and saved against this lesson.</p><textarea value={notes} onChange={e=>{setNotes(e.target.value);setNoteState("")}} rows={6} maxLength={20000} className="mt-4 w-full resize-y rounded-xl border border-white/10 bg-[#080b0f] p-4 text-sm leading-6 outline-none focus:border-[#d7ad35]/40" placeholder="Capture key ideas, questions, examples or things you want to revisit…"/><div className="mt-3 flex flex-wrap items-center justify-between gap-3"><span className="text-xs text-slate-600">{notes.length}/20,000 characters</span><button onClick={()=>void saveNotes()} disabled={noteBusy} className="inline-flex items-center gap-2 rounded-xl bg-[#d7ad35] px-4 py-3 text-sm font-bold text-black disabled:opacity-50"><Save size={14}/>{noteBusy?"Saving…":"Save notes"}</button></div>{noteError&&<p role="alert" className="mt-3 text-xs leading-5 text-amber-200/80">{noteError}</p>}</div>}
 {current&&<div className="mt-6 flex flex-wrap items-center justify-between gap-4"><p className="text-xs leading-5 text-slate-600">Marking a lesson complete records learning activity; it does not independently verify a skill.</p><button onClick={()=>saveProgress(100,0,true)} className="rounded-xl bg-[#d7ad35] px-5 py-3 font-semibold text-black">Mark lesson complete</button></div>}
 </section></div></Shell>
}