"use client";
import{useEffect,useMemo,useRef,useState}from"react";
import Shell from"../../../../components/dashboard/Shell";
import EmptyState from"../../../../components/feedback/EmptyState";
import{request}from"../../../../lib/api/client";
import{FileText,Save,Sparkles,CheckCircle2,ClipboardCheck,Send,MessageCircle}from"lucide-react";
export default function LearningPlayer({params}:{params:{courseId:string}}){
 const[d,setD]=useState<any>(),[err,setErr]=useState(""),[media,setMedia]=useState<any>({videos:[],resources:[]}),[current,setCurrent]=useState<any>(null),[notes,setNotes]=useState(""),[noteBusy,setNoteBusy]=useState(false),[noteState,setNoteState]=useState(""),[noteError,setNoteError]=useState("");
 const lastSaved=useRef(0);const [activities,setActivities]=useState<any>({quizzes:[],assignments:[],projects:[]}),[quizData,setQuizData]=useState<any>(null),[quizAnswers,setQuizAnswers]=useState<any>({}),[quizResult,setQuizResult]=useState<any>(null),[quizBusy,setQuizBusy]=useState(false),[quizError,setQuizError]=useState(""),[assignmentData,setAssignmentData]=useState<any>(null),[assignmentText,setAssignmentText]=useState(""),[assignmentFile,setAssignmentFile]=useState(""),[assignmentBusy,setAssignmentBusy]=useState(false),[assignmentError,setAssignmentError]=useState(""),[projectSubmissions,setProjectSubmissions]=useState<any[]>([]),[projectId,setProjectId]=useState(""),[projectForm,setProjectForm]=useState<any>({title:"",description:"",repository_url:"",live_url:"",submission_url:""}),[projectBusy,setProjectBusy]=useState(false),[projectError,setProjectError]=useState(""),[projectNotice,setProjectNotice]=useState("");
 useEffect(()=>{request<any>("/progress/courses/"+encodeURIComponent(params.courseId)).then(x=>setD(x.progress)).catch(x=>setErr(x.message||"Course progress could not be loaded."));request<any>("/progress/courses/"+encodeURIComponent(params.courseId)+"/activities").then(setActivities).catch(()=>setActivities({quizzes:[],assignments:[],projects:[]}));request<any>("/evidence/projects/me").then(x=>setProjectSubmissions(x.submissions||[])).catch(()=>setProjectSubmissions([]));},[params.courseId]);
 const lessons=useMemo(()=>d?.modules?.flatMap((m:any)=>m.lessons||[])||[],[d]);
 useEffect(()=>{if(!current&&lessons.length)setCurrent(lessons.find((l:any)=>!l.progress?.completed)||lessons[0])},[lessons,current]);
 useEffect(()=>{if(!current)return;lastSaved.current=0;setMedia({videos:[],resources:[]});setNotes("");setNoteState("");setNoteError("");request<any>("/progress/lessons/"+encodeURIComponent(current.id)+"/media").then(setMedia).catch(x=>setErr(x.message||"Lesson media could not be loaded."));request<any>("/progress/lessons/"+encodeURIComponent(current.id)+"/notes").then(x=>setNotes(x.note?.content||"")).catch(x=>setNoteError(x.message||"Lesson notes are not available for this lesson."));},[current?.id]);
 const saveProgress=(percent:number,position:number,completed=false)=>{if(!current)return;request<any>("/progress/lessons/"+encodeURIComponent(current.id),{method:"PUT",body:JSON.stringify({progress_percent:Math.max(0,Math.min(100,Math.round(percent))),completed,last_position_seconds:Math.max(0,Math.round(position))})}).then(x=>setD(x.course_progress)).catch(x=>setErr(x.message||"Progress could not be saved."));};
 async function saveNotes(){if(!current)return;setNoteBusy(true);setNoteError("");setNoteState("");try{await request("/progress/lessons/"+encodeURIComponent(current.id)+"/notes",{method:"PUT",body:JSON.stringify({content:notes})});setNoteState("Notes saved to your account.");}catch(e:any){setNoteError(e.message||"Notes could not be saved.");}finally{setNoteBusy(false)}}
 const lessonQuizzes=(activities.quizzes||[]).filter((q:any)=>String(q.lesson_id)===String(current?.id));
 const lessonAssignments=(activities.assignments||[]).filter((a:any)=>String(a.lesson_id)===String(current?.id));
 const showProjects=current?.lesson_type==="project"||String(current?.id)===String(lessons[lessons.length-1]?.id);
 async function startQuiz(id:string){setQuizError("");setQuizResult(null);setQuizAnswers({});setQuizBusy(true);try{const r=await request<any>("/progress/quizzes/"+encodeURIComponent(id));setQuizData(r);}catch(e:any){setQuizError(e.message||"Quiz could not be loaded.");}finally{setQuizBusy(false)}}
 async function submitQuiz(e:any){e.preventDefault();if(!quizData?.quiz?.id)return;setQuizBusy(true);setQuizError("");try{const r=await request<any>("/progress/quizzes/"+encodeURIComponent(quizData.quiz.id)+"/attempts",{method:"POST",body:JSON.stringify({answers:quizAnswers})});setQuizResult(r);setQuizData((old:any)=>({...old,attempts:[r.attempt,...(old.attempts||[])]}));}catch(e:any){setQuizError(e.message||"Quiz could not be submitted.");}finally{setQuizBusy(false)}}
 async function openAssignment(id:string){setAssignmentError("");setAssignmentData(null);setAssignmentText("");setAssignmentFile("");try{const r=await request<any>("/progress/assignments/"+encodeURIComponent(id));setAssignmentData(r);}catch(e:any){setAssignmentError(e.message||"Assignment could not be loaded.");}}
 async function submitAssignment(e:any){e.preventDefault();if(!assignmentData?.assignment?.id)return;setAssignmentBusy(true);setAssignmentError("");try{const r=await request<any>("/progress/assignments/"+encodeURIComponent(assignmentData.assignment.id)+"/submissions",{method:"POST",body:JSON.stringify({submission_text:assignmentText,file_url:assignmentFile||null})});setAssignmentData((old:any)=>({...old,submissions:[r.submission,...(old.submissions||[])]}));setAssignmentText("");setAssignmentFile("");}catch(e:any){setAssignmentError(e.message||"Assignment submission failed.");}finally{setAssignmentBusy(false)}}
 async function submitProject(e:any){e.preventDefault();if(!projectId)return;setProjectBusy(true);setProjectError("");setProjectNotice("");try{const r=await request<any>("/evidence/projects/"+encodeURIComponent(projectId)+"/submissions",{method:"POST",body:JSON.stringify(projectForm)});setProjectSubmissions((old:any)=>[r.submission,...old]);setProjectNotice("Project submitted for review.");setProjectId("");setProjectForm({title:"",description:"",repository_url:"",live_url:"",submission_url:""});}catch(e:any){setProjectError(e.message||"Project submission failed.");}finally{setProjectBusy(false)}}
 function askAI(){const context="Course: "+(d.course?.title||d.title||"Current course")+"\nLesson: "+(current?.title||"Current lesson")+"\n\n"+((current?.content||"No lesson text is available. Use the lesson title and my question as context.").slice(0,8000))+"\n\nPlease help me understand this lesson. Explain the key ideas and give a practical example.";sessionStorage.setItem("learnora_ai_context",context);location.href="/dashboard/ai";}
 if(err&&!d)return <Shell active="learning"><EmptyState title="Learning unavailable" message={err}/></Shell>;
 if(!d)return <Shell active="learning"><p className="text-slate-500">Loading your course…</p></Shell>;
 const video=media.videos?.[0];
 return <Shell active="learning"><div className="grid min-w-0 gap-5 xl:grid-cols-[17rem_minmax(0,1fr)] xl:gap-6">
 <aside className="h-fit border border-white/[.1] bg-[#11171e] p-4 xl:sticky xl:top-24 xl:max-h-[calc(100vh-7rem)] xl:overflow-y-auto"><p className="mb-2 text-xs uppercase tracking-[.2em] gold">Course progress</p><h2 className="text-lg font-semibold">{d.course?.title||d.title||"Your course"}</h2><div className="mb-5 mt-4 text-3xl font-semibold">{d.progress_percent||0}%</div><div className="mb-4 h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-[#d7ad35]" style={{width:Math.max(0,Math.min(100,d.progress_percent||0))+"%"}}/></div>{d.modules?.map((m:any)=><div key={m.id} className="mb-4"><p className="px-2 pb-2 text-[10px] uppercase tracking-[.14em] text-slate-600">{m.title}</p>{(m.lessons||[]).map((l:any)=><button key={l.id} onClick={()=>setCurrent(l)} className={"mb-1 w-full rounded-xl p-3 text-left text-sm "+(current?.id===l.id?"bg-[#d7ad35]/10 text-[#f2d477]":"text-slate-400 hover:bg-white/[.03]")}>{l.title}<span className="ml-2 text-xs text-slate-700">{l.progress?.completed?"✓":""}</span></button>)}</div>)}</aside>
 <section className="min-w-0 border border-white/[.1] bg-[#11171e] p-5 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[.2em] text-slate-600">Lesson {current?.lesson_type?"· "+current.lesson_type:""}</p><h1 className="mt-2 font-display text-4xl">{current?.title||"Select a lesson"}</h1></div>{current&&<div className="flex flex-wrap gap-2"><button onClick={askAI} className="inline-flex items-center gap-2 rounded-xl border border-[#d7ad35]/20 bg-[#d7ad35]/[.05] px-4 py-3 text-sm font-semibold gold"><Sparkles size={15}/> Ask AI about this lesson</button><a href={"/dashboard/community?course_id="+encodeURIComponent(params.courseId)} className="inline-flex items-center gap-2 rounded-xl border border-white/10 px-4 py-3 text-sm font-semibold text-slate-300 hover:text-white"><MessageCircle size={15}/> Course discussion</a></div>}</div>
 {video?.signed_url?<video key={video.id} className="mt-8 aspect-video w-full bg-black object-contain" controls preload="metadata" src={video.signed_url} onTimeUpdate={e=>{const el=e.currentTarget;if(el.currentTime-lastSaved.current>=15){lastSaved.current=el.currentTime;saveProgress(el.duration?el.currentTime/el.duration*100:0,el.currentTime)}}} onEnded={e=>saveProgress(100,e.currentTarget.currentTime,true)}/>:video?.provider==="youtube"&&video?.external_video_id?<iframe title={current?.title||"Lesson video"} className="mt-8 aspect-video w-full bg-black" src={"https://www.youtube.com/embed/"+encodeURIComponent(video.external_video_id)} allowFullScreen/>:video?.provider==="vimeo"&&video?.external_video_id?<iframe title={current?.title||"Lesson video"} className="mt-8 aspect-video w-full bg-black" src={"https://player.vimeo.com/video/"+encodeURIComponent(video.external_video_id)} allowFullScreen/>:<div className="mt-8 border border-dashed border-white/[.12] p-6 text-sm text-slate-500">{current?.content?"Text-based lesson material":"This lesson does not have video or text content yet."}</div>}
 {current?.content&&<article className="mt-6 whitespace-pre-wrap text-sm leading-8 text-slate-300">{current.content}</article>}
 {media.resources?.length>0&&<div className="mt-7"><h2 className="font-semibold">Lesson resources</h2><div className="mt-3 grid gap-2">{media.resources.map((r:any)=><a key={r.id} href={r.signed_url||r.external_url||"#"} target="_blank" rel="noreferrer" className="rounded-xl border border-white/[.07] p-3 text-sm text-slate-400 hover:text-slate-200">{r.title}</a>)}</div></div>}
 {current&&<section className="mt-8 border-t border-white/[.1] pt-6"><div className="flex items-center gap-3"><ClipboardCheck className="gold" size={19}/><div><h2 className="font-semibold">Assessment and practical work</h2><p className="mt-1 text-xs leading-5 text-slate-500">Published activities attached to this course.</p></div></div>
 <div className="mt-5 grid gap-3 sm:grid-cols-2">
 {lessonQuizzes.map((q:any)=><article key={q.id} className="border border-white/[.1] bg-[#0c1015] p-4"><p className="text-xs uppercase tracking-[.14em] gold">Quiz</p><h3 className="mt-2 font-semibold">{q.title}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{q.description||"Test your understanding."} · Pass mark {q.passing_score??70}%</p><button onClick={()=>void startQuiz(String(q.id))} disabled={quizBusy} className="mt-4 rounded-lg border border-white/10 px-3 py-2 text-xs font-semibold disabled:opacity-50">{quizBusy?"Loading…":"Open quiz"}</button></article>)}
 {lessonAssignments.map((a:any)=><article key={a.id} className="border border-white/[.1] bg-[#0c1015] p-4"><p className="text-xs uppercase tracking-[.14em] gold">Assignment</p><h3 className="mt-2 font-semibold">{a.title}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{a.description||a.instructions||"Submit work for review."}{a.max_score ? " · "+a.max_score+" points" : ""}</p><button onClick={()=>void openAssignment(String(a.id))} className="mt-4 rounded-lg border border-white/10 px-3 py-2 text-xs font-semibold">Open assignment</button></article>)}
 {showProjects&&(activities.projects||[]).map((p:any)=><article key={p.id} className="border border-white/[.1] bg-[#0c1015] p-4"><p className="text-xs uppercase tracking-[.14em] gold">Project</p><h3 className="mt-2 font-semibold">{p.title}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{p.description||p.instructions||"Build and submit a practical project."}</p><button onClick={()=>{setProjectId(String(p.id));setProjectError("");setProjectNotice("");setProjectForm({title:p.title||"",description:"",repository_url:"",live_url:"",submission_url:""})}} className="mt-4 rounded-lg border border-white/10 px-3 py-2 text-xs font-semibold">Submit project</button></article>)}
 {!lessonQuizzes.length&&!lessonAssignments.length&&!(showProjects&&(activities.projects||[]).length)&&<div className="sm:col-span-2 rounded-xl border border-dashed border-white/10 p-5 text-sm text-slate-500">No published quiz or assignment is attached to this lesson.</div>}
 </div>
 {quizData&&<div className="mt-5 rounded-xl border border-[#d7ad35]/20 bg-[#d7ad35]/[.03] p-4"><div className="flex items-center justify-between gap-3"><h3 className="font-semibold">{quizData.quiz?.title}</h3><button onClick={()=>{setQuizData(null);setQuizResult(null)}} className="text-xs text-slate-500">Close</button></div>{quizError&&<p role="alert" className="mt-3 text-sm text-amber-200">{quizError}</p>}
 {!quizResult&&<form onSubmit={submitQuiz} className="mt-4 space-y-4">{(quizData.questions||[]).map((q:any,i:number)=><fieldset key={q.id} className="border border-white/[.1] bg-[#0c1015] p-4"><legend className="px-1 text-sm">{i+1}. {q.question}</legend><div className="mt-3 grid gap-2">{optionList(q).map((o:any,j:number)=>{const value=optionValue(o);return <label key={j} className="flex items-start gap-3 rounded-lg border border-white/[.06] p-3 text-sm text-slate-300"><input type="radio" name={q.id} checked={quizAnswers[String(q.id)]===value} onChange={()=>setQuizAnswers((old:any)=>({...old,[String(q.id)]:value}))} className="mt-1 accent-[#d7ad35]"/>{optionLabel(o)}</label>})}</div></fieldset>)}<button disabled={quizBusy||!(quizData.questions||[]).length||(quizData.questions||[]).some((q:any)=>!["multiple_choice","single_choice","mcq","true_false","boolean"].includes(String(q.question_type||"").toLowerCase()))} className="rounded-xl bg-[#d7ad35] px-4 py-3 text-sm font-bold text-black disabled:opacity-50">{quizBusy?"Submitting…":"Submit answers"}</button></form>}
 {quizResult&&<div className="mt-4"><div className={"rounded-xl p-4 "+(quizResult.attempt?.passed?"bg-emerald-300/[.06] text-emerald-200":"bg-amber-300/[.06] text-amber-100")}><p className="text-2xl font-semibold">{quizResult.attempt?.score??0}%</p><p className="mt-1 text-sm">{quizResult.attempt?.passed?"Pass mark reached":"Review the explanations and keep practising"}</p></div><div className="mt-3 space-y-2">{(quizResult.review||[]).map((r:any)=><div key={r.question_id} className="rounded-lg border border-white/[.06] p-3 text-xs leading-6"><p>{r.correct?"Correct":"Incorrect"} · Answer: {String(r.correct_answer??"Not supplied")}</p>{r.explanation&&<p className="mt-1 text-slate-500">{r.explanation}</p>}</div>)}</div></div>}</div>}
 {assignmentData&&<div className="mt-5 rounded-xl border border-white/[.07] p-4"><div className="flex items-center justify-between gap-3"><h3 className="font-semibold">{assignmentData.assignment?.title}</h3><button onClick={()=>setAssignmentData(null)} className="text-xs text-slate-500">Close</button></div><p className="mt-3 whitespace-pre-wrap text-sm leading-7 text-slate-400">{assignmentData.assignment?.instructions||assignmentData.assignment?.description}</p><form onSubmit={submitAssignment} className="mt-4 space-y-3"><label className="block text-xs text-slate-400">Your response<textarea value={assignmentText} onChange={e=>setAssignmentText(e.target.value)} rows={5} maxLength={20000} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 p-3 text-sm outline-none focus:border-[#d7ad35]/40"/></label><label className="block text-xs text-slate-400">HTTPS link (optional)<input type="url" value={assignmentFile} onChange={e=>setAssignmentFile(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 p-3 text-sm outline-none focus:border-[#d7ad35]/40" placeholder="https://…"/></label><button disabled={assignmentBusy||(!assignmentText.trim()&&!assignmentFile.trim())} className="rounded-xl bg-[#d7ad35] px-4 py-3 text-sm font-bold text-black disabled:opacity-50">{assignmentBusy?"Submitting…":"Submit assignment"}</button></form>{assignmentError&&<p role="alert" className="mt-3 text-xs text-amber-200">{assignmentError}</p>}{(assignmentData.submissions||[]).map((s:any)=><p key={s.id} className="mt-3 rounded-lg border border-white/[.06] p-3 text-xs text-slate-400">Submission status: {s.status}{s.score!=null?" · Score: "+s.score:""}{s.feedback?" · "+s.feedback:""}</p>)}</div>}
 {projectId&&<form onSubmit={submitProject} className="mt-5 rounded-xl border border-white/[.07] p-4"><div className="flex items-center justify-between"><h3 className="font-semibold">Project submission</h3><button type="button" onClick={()=>setProjectId("")} className="text-xs text-slate-500">Close</button></div>{(["title","repository_url","live_url","submission_url"] as string[]).map(key=><label key={key} className="mt-3 block text-xs text-slate-400">{key.replaceAll("_"," ")}<input value={projectForm[key]} onChange={e=>setProjectForm((x:any)=>({...x,[key]:e.target.value}))} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 p-3 text-sm outline-none focus:border-[#d7ad35]/40"/></label>)}<label className="mt-3 block text-xs text-slate-400">Describe your contribution<textarea value={projectForm.description} onChange={e=>setProjectForm((x:any)=>({...x,description:e.target.value}))} rows={4} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 p-3 text-sm outline-none focus:border-[#d7ad35]/40"/></label><button disabled={projectBusy} className="mt-4 rounded-xl bg-[#d7ad35] px-4 py-3 text-sm font-bold text-black disabled:opacity-50">{projectBusy?"Submitting…":"Submit project"}</button>{projectError&&<p role="alert" className="mt-3 text-xs text-amber-200">{projectError}</p>}</form>}
 {projectNotice&&<p role="status" className="mt-4 text-xs text-emerald-200">{projectNotice}</p>}
 </section>}
 {current&&<div className="mt-8 border-t border-white/[.1] pt-6"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><FileText className="gold" size={18}/><h2 className="font-semibold">My lesson notes</h2></div>{noteState&&<span className="inline-flex items-center gap-1 text-xs text-emerald-200"><CheckCircle2 size={13}/>{noteState}</span>}</div><p className="mt-2 text-xs leading-5 text-slate-500">Notes are private to your account and saved against this lesson.</p><textarea value={notes} onChange={e=>{setNotes(e.target.value);setNoteState("")}} rows={6} maxLength={20000} className="mt-4 w-full resize-y rounded-xl border border-white/10 bg-[#080b0f] p-4 text-sm leading-6 outline-none focus:border-[#d7ad35]/40" placeholder="Capture key ideas, questions, examples or things you want to revisit…"/><div className="mt-3 flex flex-wrap items-center justify-between gap-3"><span className="text-xs text-slate-600">{notes.length}/20,000 characters</span><button onClick={()=>void saveNotes()} disabled={noteBusy} className="inline-flex items-center gap-2 rounded-xl bg-[#d7ad35] px-4 py-3 text-sm font-bold text-black disabled:opacity-50"><Save size={14}/>{noteBusy?"Saving…":"Save notes"}</button></div>{noteError&&<p role="alert" className="mt-3 text-xs leading-5 text-amber-200/80">{noteError}</p>}</div>}
 {current&&<div className="mt-6 flex flex-wrap items-center justify-between gap-4"><p className="text-xs leading-5 text-slate-600">Marking a lesson complete records learning activity; it does not independently verify a skill.</p><button onClick={()=>saveProgress(100,0,true)} className="rounded-xl bg-[#d7ad35] px-5 py-3 font-semibold text-black">Mark lesson complete</button></div>}
 </section></div></Shell>
}
function optionList(q:any):any[]{if(Array.isArray(q.options))return q.options;if(q.options&&typeof q.options==="object")return Object.entries(q.options).map(([value,label])=>({value,label}));if(["true_false","boolean"].includes(String(q.question_type||"").toLowerCase()))return ["True","False"];return []}
function optionValue(o:any):string{return String(typeof o==="string"?o:o?.value??o?.label??o?.text??"")}
function optionLabel(o:any):string{return String(typeof o==="string"?o:o?.label??o?.text??o?.value??"")}
