import Logo from "../../components/brand/Logo";

const sections = [
["1. Who we are", "Learnora ME is a learning platform that supports individual learners, instructors and creators, and organisations. Learnora may provide services directly and through participating organisations. The legal entity responsible for Learnora ME and its privacy contact details will be published here when finalised. Until then, do not use this page as a substitute for contacting the platform through an available support channel."],
["2. Personal data we collect", "Depending on how you use Learnora, we may process account details such as your name and email address; authentication and account-security records; organisation and course memberships; enrolment, learning progress, assessment, project and portfolio evidence; creator or instructor application details; support communications; subscription, transaction and billing-status records; and technical data such as log, device, browser and security events. We aim to collect only information reasonably needed for the relevant feature."],
["3. Why we use it", "We use information to create and secure accounts, verify email addresses, deliver courses and learning tools, record progress, operate organisation workspaces, support instructors and creators, manage subscriptions and access entitlements, prevent fraud and abuse, respond to requests, improve platform reliability, and meet applicable legal obligations. Where a feature uses personal data for a new purpose, we will provide additional information where required."],
["4. Lawful basis", "Where applicable, processing is based on steps needed to provide a service or perform a contract, compliance with legal obligations, legitimate interests such as platform security and service improvement, or consent where consent is the appropriate basis. You may withdraw consent where processing relies on it; withdrawal does not affect processing that took place before withdrawal or processing supported by another lawful basis."],
["5. Learning records and AI features", "Learnora may process prompts, conversation history, course context, submitted answers, project details and learning progress to provide AI tutoring, practice, coaching, feedback and related features. Do not submit passwords, payment-card details, sensitive personal information, or another person's confidential data to AI tools. AI output may be inaccurate and is intended to support learning, not replace your judgement or qualified professional advice. AI providers may process the information sent to them to generate a response under their applicable service terms; provider and retention details should be confirmed in the live platform configuration before launch."],
["6. Payments and subscriptions", "If you purchase a paid plan, payment processing may be handled by an external payment provider. Learnora may receive transaction identifiers, payment status, plan, renewal and limited billing information, but should not need to store your full payment-card credentials. Provider-specific privacy terms apply to information collected directly by the payment provider."],
["7. Organisations, instructors and creators", "If you join through an organisation, relevant administrators may be able to see membership details and learning records needed to manage the programme, such as enrolment, course progress, assessment or participation. Instructors may access information needed to deliver and assess learning. Creator applications and payout administration may involve identity, tax, payment or business information where required. The scope of access should be limited to the person's responsibilities and the relevant service."],
["8. Sharing and international transfers", "We may share information with service providers that support hosting, databases, authentication, email delivery, AI, payments, security, analytics and customer support; with an organisation or instructor where needed to deliver your programme; or with authorities where legally required. Providers may process data in countries other than your own. We intend to use appropriate safeguards and contractual controls where required by applicable law."],
["9. Retention and security", "We retain personal data for as long as reasonably needed for the purposes described, including account operation, learning records, dispute handling, security, financial records and legal obligations. Retention periods vary by data type and service. We use technical and organisational measures intended to protect information, but no internet service can guarantee absolute security. Please use a unique password and report suspected account compromise promptly."],
["10. Your rights and choices", "Subject to applicable law, you may have rights to request access to personal data, correction, deletion, restriction or objection to certain processing, portability, or withdrawal of consent. You may also complain to the relevant data-protection authority. Some records may need to be retained to provide the service or comply with law. To exercise a right, contact Learnora using the privacy contact channel that will be published here; legal identity and contact details remain to be completed by the platform owner."],
["11. Children", "Learnora is not intended for children who are not legally able to consent to the relevant processing without appropriate parent or guardian involvement. Organisations serving younger learners must ensure they have appropriate authority, notices and safeguards before enrolling them. Do not create an account using another person's details."],
["12. Cookies and similar technologies", "Learnora may use essential storage and similar technologies for authentication, security, preferences and core platform operation. If non-essential analytics or advertising technologies are introduced, the platform should provide an appropriate notice and choice mechanism before they are activated where required by law. Browser settings may also allow you to manage some storage technologies."],
["13. Changes", "We may update this policy when the platform, its providers or applicable requirements change. The effective date below should be updated whenever a material revision is published. Where required, we will provide additional notice or seek consent."],
];
export default function PrivacyPage(){return <main className="min-h-screen bg-[#07090c] px-5 py-10 text-white"><div className="mx-auto max-w-4xl"><a href="/"><Logo/></a><p className="mt-12 text-xs uppercase tracking-[.25em] text-[#d7ad35]">Legal · Privacy</p><h1 className="mt-3 font-display text-5xl">Privacy Policy</h1><p className="mt-4 text-sm text-slate-500">Effective date: 10 October 2026 · Draft for operational review</p><p className="mt-8 rounded-xl border border-[#d7ad35]/20 bg-[#d7ad35]/[.05] p-4 text-sm leading-6 text-slate-300">This policy is tailored to the current Learnora ME product scope. Before public launch, the platform owner must complete the legal entity, privacy contact, provider/retention details and any other marked operational facts, then obtain qualified legal and data-protection review. It is not a legal certification.</p><div className="mt-10 space-y-8">{sections.map(([title,body])=><section key={title}><h2 className="text-xl font-semibold">{title}</h2><p className="mt-3 leading-7 text-slate-400">{body}</p></section>)}</div><p className="mt-12 border-t border-white/10 pt-6 text-xs text-slate-600">Learnora ME · Privacy Policy</p><a href="/terms" className="mt-4 inline-block text-sm text-[#f2d477]">Read Terms of Use →</a></div></main>}