"use client";
import{useEffect,useState}from"react";
import{currentUser}from"../../../../lib/api";
import{adminCourses,createCourse}from"../../../../lib/api/admin";
import Shell from"../../../../components/dashboard/Shell";
import SectionHeader from"../../../../components/dashboard/SectionHeader";
import DataTable from"../../../../components/dashboard/DataTable";
import ActionButton from"../../../../components/dashboard/ActionButton";
export default function CoursesAdmin(){const[u,setU]=useState<any>(),[rows,setRows]=useState<any[]>([]),[open,setOpen]=useState(false),[err,setErr]=useState("");const load=()=>adminCourses().then(x=>setRows(x.courses||[])).catch(e=>setErr(e.message));useEffect(()=>{currentUser().then(x=>{if(x.account_type!=="admin")location.href="/dashboard";else{setU(x);load()}}).catch(()=>location.href="/login")},[]);if(!u)return <div className="p-10">Loading…</div>;return <Shell admin role={u.role} active="courses"><SectionHeader eyebrow="Course operations" title="Courses" description="Create and inspect real Learnora courses." action={<ActionButton onClick={()=>setOpen(true)}>Create course</ActionButton>}/>{err&&<p className="mb-5 text-sm text-red-300">{err}</p>}<DataTable rows={rows} columns={[{key:"title",label:"Course"},{key:"ownership",label:"Owner"},{key:"status",label:"Status"},{key:"level",label:"Level"},{key:"estimated_hours",label:"Hours"}]}/>{open&&<CourseForm onDone={()=>{setOpen(false);load()}} onClose={()=>setOpen(false)}/>}</Shell>}
function CourseForm({onDone,onClose}:{onDone:()=>void;onClose:()=>void}){const[f,setF]=useState({title:"",slug:"",short_description:"",description:"",level:"beginner",status:"draft",ownership:"learnora",estimated_hours:""}),[busy,setBusy]=useState(false),[err,setErr]=useState("");const set=(k:string,v:string)=>setF(x=>({...x,[k]:v}));const submit=async()=>{setBusy(true);setErr("");try{await createCourse({...f,estimated_hours:f.estimated_hours?Number(f.estimated_hours):null});onDone()}catch(e:any){setErr(e.message)}finally{setBusy(false)}};return <div className="fixed inset-0 z-50 grid place-items-center bg-black/75 p-5"><div className="w-full max-w-2xl rounded-3xl border border-white/10 bg-[#0e1319] p-7"><div className="flex justify-between"><h2 className="text-2xl font-semibold">Create course</h2><button onClick={onClose} className="text-slate-500">Close</button></div><div className="mt-6 grid gap-4 sm:grid-cols-2">{["title","slug","short_description","description","estimated_hours"].map(k=><input key={k} value={(f as any)[k]} onChange={e=>set(k,e.target.value)} placeholder={k.replaceAll("_"," ")} className="rounded-xl border border-white/10 bg-black/20 px-4 py-3 outline-none"/>)}</div><div className="mt-4 grid grid-cols-2 gap-4"><select value={f.level} onChange={e=>set("level",e.target.value)} className="rounded-xl bg-black/20 p-3"><option>beginner</option><option>intermediate</option><option>advanced</option><option>mixed</option></select><select value={f.ownership} onChange={e=>set("ownership",e.target.value)} className="rounded-xl bg-black/20 p-3"><option>learnora</option><option>organisation</option></select></div>{err&&<p className="mt-4 text-sm text-red-300">{err}</p>}<div className="mt-6 flex justify-end gap-3"><ActionButton onClick={onClose}>Cancel</ActionButton><ActionButton disabled={busy} onClick={submit}>{busy?"Creating…":"Create"}</ActionButton></div></div></div>}