"use client";
import {useEffect,useState} from "react";
import Shell from "./Shell";
import {contentCourses,contentCourse,contentModules,contentLessons,contentLesson,contentLessonMedia,courseStructure,updateCourse,archiveCourse,createModule,createLesson,updateLesson,archiveModule,archiveLesson,reorderModules,reorderLessons,createVideo,createResource} from "../lib/content";
import {teamMe} from "../lib/api";

const types=["video","article","text","practice","quiz","assignment","project","mixed"];
const providers=["supabase","cloudflare","mux","bunny","vimeo","youtube","external","other"];

export default function ContentManager(){
 const [me,setMe]=useState<any>();const [courses,setCourses]=useState<any[]>([]);const [course,setCourse]=useState("");const [courseData,setCourseData]=useState<any>(null);const [courseSummary,setCourseSummary]=useState<any>(null);const [courseTitle,setCourseTitle]=useState("");const [courseSlug,setCourseSlug]=useState("");const [courseDesc,setCourseDesc]=useState("");const [courseLevel,setCourseLevel]=useState("beginner");const [courseStatus,setCourseStatus]=useState("draft");const [mods,setMods]=useState<any[]>([]);const [mod,setMod]=useState("");const [lessons,setLessons]=useState<any[]>([]);const [lessonId,setLessonId]=useState("");const [lesson,setLesson]=useState<any>();const [media,setMedia]=useState<any>({videos:[],resources:[]});const [error,setError]=useState("");const [notice,setNotice]=useState("");const [busy,setBusy]=useState(false);
 const [newMod,setNewMod]=useState("");const [newLesson,setNewLesson]=useState("");const [title,setTitle]=useState("");const [desc,setDesc]=useState("");const [body,setBody]=useState("");const [type,setType]=useState("mixed");const [status,setStatus]=useState("draft");const [duration,setDuration]=useState("");
 const [video,setVideo]=useState({provider:"youtube",title:"",external_video_id:"",storage_path:"",status:"pending",is_private:true});const [resource,setResource]=useState({title:"",resource_type:"document",external_url:"",storage_path:""});
 const act=async(fn:()=>Promise<void>,msg:string)=>{setBusy(true);setError("");setNotice("");try{await fn();setNotice(msg)}catch(e:any){setError(e.message||"Operation failed")}finally{setBusy(false)}};
 const loadMods=async()=>{const d=await contentModules(course);setMods(d.modules||[]);if(!d.modules?.some((x:any)=>String(x.id)===mod))setMod(d.modules?.[0]?String(d.modules[0].id):"")};
 const loadLessons=async()=>{const d=await contentLessons(mod);setLessons(d.lessons||[]);if(!d.lessons?.some((x:any)=>String(x.id)===lessonId))setLessonId(d.lessons?.[0]?String(d.lessons[0].id):"")};
 const loadLesson=async()=>{if(!lessonId)return;const [l,m]=await Promise.all([contentLesson(lessonId),contentLessonMedia(lessonId)]);const x=l.lesson;setLesson(x);setMedia(m);setTitle(x?.title||"");setDesc(x?.description||"");setBody(x?.content||"");setType(x?.lesson_type||"mixed");setStatus(x?.status||"draft");setDuration(x?.duration_minutes==null?"":String(x.duration_minutes))};
 useEffect(()=>{Promise.all([teamMe(),contentCourses()]).then(([a,b])=>{setMe(a);setCourses(b.courses||[]);if(b.courses?.[0])setCourse(String(b.courses[0].id))}).catch(e=>setError(e.message))},[]);
 useEffect(()=>{if(course){loadMods().catch(e=>setError(e.message));courseStructure(course).then(setCourseSummary).catch(e=>setError(e.message));contentCourse(course).then(d=>{const x=d.course;setCourseData(x);setCourseTitle(x?.title||"");setCourseSlug(x?.slug||"");setCourseDesc(x?.description||"");setCourseLevel(x?.level||"beginner");setCourseStatus(x?.status||"draft")}).catch(e=>setError(e.message))}else{setCourseSummary(null);setCourseData(null)}},[course]);
 useEffect(()=>{if(mod)loadLessons().catch(e=>setError(e.message))},[mod]);
 useEffect(()=>{loadLesson().catch(e=>setError(e.message))},[lessonId]);
 if(!me)return <div className="p-10 text-slate-400">Loading secure workspace…</div>;
 return <Shell roles={me.roles||[]} active="content"><h1 className="text-4xl font-semibold">Course content</h1><p className="mt-2 text-slate-500">Live course hierarchy, lessons and media metadata.</p>
 {error&&<div className="notice error">{error}</div>}{notice&&<div className="notice ok">{notice}</div>}
 <div className="mt-6 grid gap-4 xl:grid-cols-4">
 <Box title="Courses"><select className="field" value={course} onChange={e=>setCourse(e.target.value)}>{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select>{courseData&&<div className="mt-3 space-y-2"><input className="field" value={courseTitle} onChange={e=>setCourseTitle(e.target.value)} placeholder="Course title"/><input className="field" value={courseSlug} onChange={e=>setCourseSlug(e.target.value)} placeholder="Course slug"/><textarea className="field min-h-20" value={courseDesc} onChange={e=>setCourseDesc(e.target.value)} placeholder="Course description"/><div className="grid grid-cols-2 gap-2"><select className="field" value={courseLevel} onChange={e=>setCourseLevel(e.target.value)}><option>beginner</option><option>intermediate</option><option>advanced</option><option>mixed</option></select><select className="field" value={courseStatus} onChange={e=>setCourseStatus(e.target.value)}><option>draft</option><option>published</option><option>archived</option></select></div><button className="action w-full" disabled={busy} onClick={()=>act(async()=>{await updateCourse(course,{title:courseTitle,slug:courseSlug,description:courseDesc,level:courseLevel,status:courseStatus});const d=await contentCourses();setCourses(d.courses||[])},"Course saved.")}>Save course</button><button className="danger w-full" disabled={busy||courseStatus==="archived"} onClick={()=>act(async()=>{await archiveCourse(course);const d=await contentCourses();setCourses(d.courses||[]);setCourseStatus("archived")},"Course archived.")}>Archive course</button></div>}{courseSummary&&<div className="mt-3 grid grid-cols-2 gap-2 text-xs"><div className="rounded-lg border border-white/[.06] p-2"><span className="text-slate-500">Modules</span><p className="mt-1 text-slate-200">{courseSummary.module_count??0}</p></div><div className="rounded-lg border border-white/[.06] p-2"><span className="text-slate-500">Lessons</span><p className="mt-1 text-slate-200">{courseSummary.lesson_count??0}</p></div></div>}{courseSummary&&<p className="mt-3 text-xs text-slate-500">{courseSummary.lesson_count?"Course has live curriculum content.":"Course is currently empty — ready for curriculum."}</p>}</Box>
 <Box title="Modules"><div className="flex gap-2"><input className="field" placeholder="New module" value={newMod} onChange={e=>setNewMod(e.target.value)}/><button className="action" disabled={!newMod.trim()||busy} onClick={()=>act(async()=>{const r=await createModule(course,{title:newMod,order_index:mods.length,status:"draft"});setNewMod("");await loadMods();setMod(String(r.module.id))},"Module created.")}>Add</button></div>{mods.map((m,i)=><div className={"item "+(String(m.id)===mod?"active":"")} key={m.id}><button onClick={()=>setMod(String(m.id))} className="flex-1 text-left">{m.title}<span>{m.status}</span></button><button className="mini" disabled={!i} onClick={()=>act(async()=>{const a=[...mods];[a[i-1],a[i]]=[a[i],a[i-1]];setMods(a);await reorderModules(course,a.map((x,j)=>({id:String(x.id),order_index:j})))},"Order saved.")}>↑</button><button className="mini" disabled={i===mods.length-1} onClick={()=>act(async()=>{const a=[...mods];[a[i],a[i+1]]=[a[i+1],a[i]];setMods(a);await reorderModules(course,a.map((x,j)=>({id:String(x.id),order_index:j})))},"Order saved.")}>↓</button></div>)}{mod&&<button className="danger mt-2" onClick={()=>act(async()=>{await archiveModule(mod);await loadMods()},"Module archived.")}>Archive module</button>}</Box>
 <Box title="Lessons"><div className="flex gap-2"><input className="field" placeholder="New lesson" value={newLesson} onChange={e=>setNewLesson(e.target.value)}/><button className="action" disabled={!newLesson.trim()||busy} onClick={()=>act(async()=>{const r=await createLesson(mod,{title:newLesson,order_index:lessons.length,lesson_type:"mixed",status:"draft"});setNewLesson("");await loadLessons();setLessonId(String(r.lesson.id))},"Lesson created.")}>Add</button></div>{lessons.map((l,i)=><div className={"item "+(String(l.id)===lessonId?"active":"")} key={l.id}><button onClick={()=>setLessonId(String(l.id))} className="flex-1 text-left">{l.title}<span>{l.lesson_type} · {l.status}</span></button><button className="mini" disabled={!i} onClick={()=>act(async()=>{const a=[...lessons];[a[i-1],a[i]]=[a[i],a[i-1]];setLessons(a);await reorderLessons(mod,a.map((x,j)=>({id:String(x.id),order_index:j})))},"Order saved.")}>↑</button><button className="mini" disabled={i===lessons.length-1} onClick={()=>act(async()=>{const a=[...lessons];[a[i],a[i+1]]=[a[i+1],a[i]];setLessons(a);await reorderLessons(mod,a.map((x,j)=>({id:String(x.id),order_index:j})))},"Order saved.")}>↓</button></div>)}</Box>
 <Box title={lesson?.title||"Lesson detail"}>{!lesson?<Muted>Select a lesson.</Muted>:<div className="space-y-3"><input className="field" value={title} onChange={e=>setTitle(e.target.value)}/><textarea className="field min-h-20" placeholder="Description" value={desc} onChange={e=>setDesc(e.target.value)}/><div className="grid grid-cols-2 gap-2"><select className="field" value={type} onChange={e=>setType(e.target.value)}>{types.map(x=><option key={x}>{x}</option>)}</select><select className="field" value={status} onChange={e=>setStatus(e.target.value)}>{["draft","published","archived"].map(x=><option key={x}>{x}</option>)}</select></div><input type="number" min="0" className="field" placeholder="Duration minutes" value={duration} onChange={e=>setDuration(e.target.value)}/><textarea className="field min-h-40" placeholder="Lesson content" value={body} onChange={e=>setBody(e.target.value)}/><button className="action" disabled={busy} onClick={()=>act(async()=>{await updateLesson(lessonId,{title,description:desc,content:body,lesson_type:type,status,duration_minutes:duration?Number(duration):null});await loadLesson()},"Lesson saved.")}>Save lesson</button><button className="danger ml-2" onClick={()=>act(async()=>{await archiveLesson(lessonId);await loadLessons()},"Lesson archived.")}>Archive</button>
 <Media lessonId={lessonId} media={media} video={video} setVideo={setVideo} resource={resource} setResource={setResource} act={act} reload={loadLesson}/></div>}</Box>
 </div></Shell>
}
function Media({lessonId,media,video,setVideo,resource,setResource,act,reload}:any){return <div className="mt-5 border-t border-white/[.07] pt-5 space-y-4"><h3 className="font-semibold">Media & resources</h3><div><p className="label">Videos</p>{media.videos.map((v:any)=><p className="mt-2 text-xs text-slate-400" key={v.id}>{v.title||"Untitled"} · {v.provider} · {v.status}</p>)}<div className="mt-2 grid gap-2"><select className="field" value={video.provider} onChange={e=>setVideo({...video,provider:e.target.value})}>{providers.map(x=><option key={x}>{x}</option>)}</select><input className="field" placeholder="Title" value={video.title} onChange={e=>setVideo({...video,title:e.target.value})}/><input className="field" placeholder="External video ID" value={video.external_video_id} onChange={e=>setVideo({...video,external_video_id:e.target.value})}/><input className="field" placeholder="Storage path" value={video.storage_path} onChange={e=>setVideo({...video,storage_path:e.target.value})}/><button className="action" onClick={()=>act(async()=>{await createVideo(lessonId,{...video,external_video_id:video.external_video_id||null,storage_path:video.storage_path||null,title:video.title||null});await reload()},"Video metadata added.")}>Add video metadata</button></div></div><div><p className="label">Resources</p>{media.resources.map((r:any)=><p className="mt-2 text-xs text-slate-400" key={r.id}>{r.title} · {r.resource_type}</p>)}<div className="mt-2 grid gap-2"><input className="field" placeholder="Resource title" value={resource.title} onChange={e=>setResource({...resource,title:e.target.value})}/><input className="field" placeholder="Resource type" value={resource.resource_type} onChange={e=>setResource({...resource,resource_type:e.target.value})}/><input className="field" placeholder="External URL" value={resource.external_url} onChange={e=>setResource({...resource,external_url:e.target.value})}/><input className="field" placeholder="Storage path" value={resource.storage_path} onChange={e=>setResource({...resource,storage_path:e.target.value})}/><button className="action" disabled={!resource.title.trim()} onClick={()=>act(async()=>{await createResource(lessonId,{...resource,external_url:resource.external_url||null,storage_path:resource.storage_path||null});setResource({title:"",resource_type:"document",external_url:"",storage_path:""});await reload()},"Resource added.")}>Add resource</button></div></div></div>}
function Box({title,children}:{title:string;children:React.ReactNode}){return <section className="panel"><h2>{title}</h2>{children}</section>}
function Muted({children}:{children:React.ReactNode}){return <p className="muted">{children}</p>}