"use client";
import {useEffect,useState} from "react";
import Shell from "./Shell";
import {teamMe} from "../lib/api";
import {organisations,organisationMembers,memberSummary,organisationContract,organisationCapacity,organisationRequests} from "../lib/operations";
export default function OrganisationWorkspace(){
 const [me,setMe]=useState<any>();const [orgs,setOrgs]=useState<any[]>([]);const [selected,setSelected]=useState<any>();const [members,setMembers]=useState<any[]>([]);const [summary,setSummary]=useState<any>();const [contract,setContract]=useState<any>();const [capacity,setCapacity]=useState<any[]>([]);const [requests,setRequests]=useState<any[]>([]);const [error,setError]=useState("");
 const load=async(id:string)=>{try{const [m,s,c,cap]=await Promise.all([organisationMembers(id),memberSummary(id),organisationContract(id),organisationCapacity(id)]);setMembers(m.members||[]);setSummary(s.summary);setContract(c.contract);setCapacity(cap.capacity||[])}catch(e:any){setError(e.message||"Unable to load organisation details")}};
 useEffect(()=>{Promise.all([teamMe(),organisations(),organisationRequests()]).then(([u,o,r])=>{setMe(u);setOrgs(o.organisations||[]);setRequests(r.requests||[])}).catch(e=>setError(e.message||"Unable to load organisations"))},[]);
 useEffect(()=>{if(selected)load(String(selected.id))},[selected]);
 if(!me)return <div className="p-10 text-slate-400">Loading secure workspace…</div>;
 return <Shell roles={me.roles||[]} active="organisations"><h1 className="text-4xl font-semibold">Organisations</h1><p className="mt-2 text-slate-500">Live tenant operations, membership, contracts and capacity.</p>{error&&<div className="notice error">{error}</div>}
 <div className="mt-7 grid gap-4 lg:grid-cols-[320px_1fr]"><section className="panel"><h2>Organisations</h2>{orgs.length?orgs.map(o=><button key={o.id} onClick={()=>setSelected(o)} className={"item "+(selected?.id===o.id?"active":"")}><span className="block text-left">{o.name}</span><span>{o.organisation_type} · {o.is_active?"active":"inactive"}</span></button>):<p className="muted">No organisations returned.</p>}<div className="mt-6 border-t border-white/[.07] pt-4"><h2>Requests</h2>{requests.slice(0,8).map(r=><div key={r.id} className="item"><span className="block">{r.organisation_name}</span><span>{r.status}</span></div>)}{!requests.length&&<p className="muted">No organisation requests.</p>}</div></section>
 <section>{!selected?<div className="panel"><p className="muted">Select an organisation to inspect its live operational state.</p></div>:<div className="space-y-4"><div className="panel"><div className="flex flex-wrap justify-between gap-3"><div><h2>{selected.name}</h2><p className="muted">{selected.slug} · {selected.organisation_type}</p></div><span className={selected.is_active?"text-emerald-300":"text-red-300"}>{selected.is_active?"Active":"Inactive"}</span></div></div>
 <div className="grid gap-4 md:grid-cols-4"><Metric label="Members" value={summary?.total??"—"}/><Metric label="Learners" value={summary?.learners??"—"}/><Metric label="Instructors" value={summary?.instructors??"—"}/><Metric label="Admins" value={summary?.admins??"—"}/></div>
 <div className="grid gap-4 lg:grid-cols-2"><div className="panel"><h2>Contract</h2>{contract?<div className="space-y-2 text-sm text-slate-400"><p><b className="text-slate-200">#{contract.contract_number}</b> · {contract.status}</p><p>{contract.start_date||"No start"} → {contract.end_date||"No end"}</p><p>{contract.currency}</p></div>:<p className="muted">No active/signed contract.</p>}</div><div className="panel"><h2>Capacity</h2>{capacity.length?capacity.map(x=><div key={x.entitlement.id} className="item"><span>{x.entitlement.entitlement_key}</span><span>{x.used} / {x.entitlement.limit_value==null?"∞":x.entitlement.limit_value}</span></div>):<p className="muted">No active contract entitlements.</p>}</div></div>
 <div className="panel"><h2>Members</h2>{members.length?<div className="divide-y divide-white/[.05]">{members.map(m=><div key={m.membership_id} className="grid gap-2 p-3 md:grid-cols-4"><span>{m.user?.name||m.user?.email||m.user_id}</span><span className="text-slate-500">{m.role}</span><span className="text-slate-500">{m.status}</span><span className="text-slate-600">{m.joined_at||"—"}</span></div>)}</div>:<p className="muted">No members.</p>}</div>
 </div>}</section></div></Shell>}
function Metric({label,value}:{label:string;value:any}){return <div className="panel"><p className="label">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></div>}