"use client";
import {useEffect,useState} from "react";
import Shell from "./Shell";
import {teamMe} from "../lib/api";
import {organisations,organisationMembers,memberSummary,organisationContract,organisationCapacity,contractPreparation,organisationRequests,updateOrganisationRequest,createOrganisation,updateOrganisation} from "../lib/operations";

const empty={name:"",slug:"",organisation_type:"academy",template:"academy",description:"",logo_url:"",brand_primary:"#d7ad35",brand_secondary:"#f2d477"};
export default function OrganisationWorkspace(){
 const [me,setMe]=useState<any>();const [requestBusy,setRequestBusy]=useState<string>("");const [orgs,setOrgs]=useState<any[]>([]);const [selected,setSelected]=useState<any>();const [members,setMembers]=useState<any[]>([]);const [summary,setSummary]=useState<any>();const [contract,setContract]=useState<any>();const [capacity,setCapacity]=useState<any[]>([]);const [requests,setRequests]=useState<any[]>([]);const [error,setError]=useState("");const [form,setForm]=useState<any>(empty);const [editing,setEditing]=useState(false);const [creating,setCreating]=useState(false);const [busy,setBusy]=useState(false);const [contractPrep,setContractPrep]=useState<any>();const [prepBusy,setPrepBusy]=useState(false);
 const load=async(id:string)=>{try{const [m,s,c,cap]=await Promise.all([organisationMembers(id),memberSummary(id),organisationContract(id),organisationCapacity(id)]);setMembers(m.members||[]);setSummary(s.summary);setContract(c.contract);setCapacity(cap.capacity||[])}catch(e:any){setError(e.message||"Unable to load organisation details")}};
 const refresh=async()=>{const d=await organisations();setOrgs(d.organisations||[])};
 useEffect(()=>{Promise.all([teamMe(),organisations(),organisationRequests()]).then(([u,o,r])=>{setMe(u);setOrgs(o.organisations||[]);setRequests(r.requests||[])}).catch(e=>setError(e.message||"Unable to load organisations"))},[]);
 useEffect(()=>{if(selected){load(String(selected.id));setContractPrep(undefined)}},[selected]);
 const edit=(o:any)=>{setSelected(o);setForm({...empty,...o});setCreating(false);setEditing(true)};
 const create=()=>{setSelected(undefined);setForm({...empty});setCreating(true);setEditing(true)};
 const save=async()=>{try{setBusy(true);setError("");const r=creating?await createOrganisation(form):await updateOrganisation(String(selected.id),form);setEditing(false);setCreating(false);await refresh();setSelected(r.organisation);await load(String(r.organisation.id))}catch(e:any){setError(e.message||"Unable to save organisation")}finally{setBusy(false)}};
 if(!me)return <div className="p-10 text-slate-400">Loading secure workspace…</div>;
 return <Shell roles={me.roles||[]} active="organisations"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-4xl font-semibold">Organisations</h1><p className="mt-2 text-slate-500">Reusable tenant layouts, branding, memberships, contracts and capacity.</p></div><button className="action" onClick={create}>New organisation</button></div>{error&&<div className="notice error">{error}</div>}
 {editing&&<div className="panel mt-6"><h2>{creating?"Create organisation":"Edit organisation"}</h2><p className="muted mb-4">This uses the shared Learnora organisation template. Creating another organisation never requires frontend code.</p><div className="grid gap-3 md:grid-cols-2"><input className="field" placeholder="Organisation name" value={form.name||""} onChange={e=>setForm({...form,name:e.target.value})}/><input className="field" placeholder="Slug" value={form.slug||""} onChange={e=>setForm({...form,slug:e.target.value})}/><select className="field" value={form.organisation_type||"academy"} onChange={e=>setForm({...form,organisation_type:e.target.value})}><option>academy</option><option>corporate</option><option>school</option><option>community</option><option>nonprofit</option></select><select className="field" value={form.template||"academy"} onChange={e=>setForm({...form,template:e.target.value})}><option>academy</option><option>corporate</option><option>school</option></select><input className="field" placeholder="Logo URL" value={form.logo_url||""} onChange={e=>setForm({...form,logo_url:e.target.value})}/><input className="field" placeholder="Primary brand colour" value={form.brand_primary||""} onChange={e=>setForm({...form,brand_primary:e.target.value})}/><input className="field" placeholder="Secondary brand colour" value={form.brand_secondary||""} onChange={e=>setForm({...form,brand_secondary:e.target.value})}/><textarea className="field md:col-span-2 min-h-24" placeholder="Description" value={form.description||""} onChange={e=>setForm({...form,description:e.target.value})}/></div><div className="mt-4 flex gap-2"><button className="action" disabled={busy||!form.name?.trim()||!form.slug?.trim()} onClick={save}>{creating?"Create organisation":"Save changes"}</button><button className="danger" onClick={()=>{setEditing(false);setCreating(false)}}>Cancel</button></div></div>}
 <div className="mt-7 grid gap-4 lg:grid-cols-[320px_1fr]"><section className="panel"><h2>Organisations</h2>{orgs.length?orgs.map(o=><button key={o.id} onClick={()=>{setSelected(o);setEditing(false)}} className={"item "+(selected?.id===o.id?"active":"")}><span className="block text-left">{o.name}</span><span>{o.template} · {o.is_active?"active":"inactive"}</span></button>):<p className="muted">No organisations returned.</p>}<div className="mt-6 border-t border-white/[.07] pt-4"><h2>Requests</h2>{requests.slice(0,8).map(r=><div key={r.id} className="item"><div><span className="block">{r.organisation_name}</span><span className="text-slate-500">{r.status}</span></div><select disabled={requestBusy===String(r.id)} value={r.status||"submitted"} onChange={async e=>{try{setRequestBusy(String(r.id));setError("");const x=await updateOrganisationRequest(String(r.id),e.target.value);setRequests(prev=>prev.map(item=>String(item.id)===String(r.id)?x.request:item))}catch(e:any){setError(e.message||"Unable to update request")}finally{setRequestBusy("")}}} className="field max-w-[190px]">{["submitted","under_review","discussion","contract_preparation","contract_sent","signed","pending_approval","active","declined","closed"].map(s=><option key={s} value={s}>{s.replaceAll("_"," ")}</option>)}</select></div>)}{!requests.length&&<p className="muted">No organisation requests.</p>}</div></section>
 <section>{!selected?<div className="panel"><p className="muted">Select an organisation to inspect its live operational state.</p></div>:<div className="space-y-4"><div className="panel"><div className="flex flex-wrap justify-between gap-3"><div className="flex gap-4 items-center">{selected.logo_url&&<img src={selected.logo_url} alt="" className="h-12 w-12 rounded-xl object-cover"/>}<div><h2>{selected.name}</h2><p className="muted">{selected.slug} · {selected.template}</p></div></div><div className="flex items-center gap-2"><span className={selected.is_active?"text-emerald-300":"text-red-300"}>{selected.is_active?"Active":"Inactive"}</span><button className="action" onClick={()=>edit(selected)}>Edit organisation</button></div></div></div>
 <div className="grid gap-4 md:grid-cols-4"><Metric label="Members" value={summary?.total??"—"}/><Metric label="Learners" value={summary?.learners??"—"}/><Metric label="Instructors" value={summary?.instructors??"—"}/><Metric label="Admins" value={summary?.admins??"—"}/></div><div className="grid gap-4 lg:grid-cols-2"><div className="panel"><div className="flex flex-wrap items-center justify-between gap-3"><h2>Contract</h2><button className="action" disabled={prepBusy} onClick={async()=>{try{setPrepBusy(true);setError("");setContractPrep(await contractPreparation(String(selected.id)))}catch(e:any){setError(e.message||"Unable to load contract preparation")}finally{setPrepBusy(false)}}}>{prepBusy?"Loading…":"Prepare contract"}</button></div>{contract?<div className="mt-3 space-y-2 text-sm text-slate-400"><p><b className="text-slate-200">#{contract.contract_number}</b> · {contract.status}</p><p>{contract.start_date||"No start"} → {contract.end_date||"No end"}</p><p>{contract.currency}</p></div>:<p className="muted mt-3">No active/signed contract.</p>}{contractPrep&&<div className="mt-4 rounded-xl border border-white/[.07] p-3 text-sm"><p className="text-slate-300">Request: {contractPrep.request?.status||"Not found"}</p><p className="text-slate-500">Terms ready: {contractPrep.ready_for_terms?"yes":"no"} · Draft-ready: {contractPrep.ready_for_draft?"yes":"no"}</p><p className="mt-2 text-slate-500">Versions: {contractPrep.versions?.length||0} · Entitlements: {contractPrep.entitlements?.length||0}</p></div>}</div><div className="panel"><h2>Capacity</h2>{capacity.length?capacity.map(x=><div key={x.entitlement.id} className="item"><span>{x.entitlement.entitlement_key}</span><span>{x.used} / {x.entitlement.limit_value==null?"∞":x.entitlement.limit_value}</span></div>):<p className="muted">No active contract entitlements.</p>}</div></div><div className="panel"><h2>Members</h2>{members.length?<div className="divide-y divide-white/[.05]">{members.map(m=><div key={m.membership_id} className="grid gap-2 p-3 md:grid-cols-4"><span>{m.user?.name||m.user?.email||m.user_id}</span><span className="text-slate-500">{m.role}</span><span className="text-slate-500">{m.status}</span><span className="text-slate-600">{m.joined_at||"—"}</span></div>)}</div>:<p className="muted">No members.</p>}</div></div>}</section></div></Shell>}
}
function Metric({label,value}:{label:string;value:any}){return <div className="panel"><p className="label">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></div>}