"use client";
import { motion } from "framer-motion";
import { BookOpen, Target, FolderKanban, FileCheck2 } from "lucide-react";
import { IMAGES } from "../../lib/constants";
const items=[
  ["01","Learn","Structured learning around useful skills.",IMAGES.learners,BookOpen,"/courses"],
  ["02","Practise","Apply concepts with exercises and feedback.",IMAGES.practice,Target,"/dashboard/practice"],
  ["03","Build","Create projects that reflect real work.",IMAGES.projects,FolderKanban,"/dashboard/projects"],
  ["04","Prove","Turn work into evidence you can explain.",IMAGES.portfolio,FileCheck2,"/dashboard/evidence"]
];
export default function Journey(){return <section className="py-24 sm:py-28"><div className="mx-auto max-w-7xl px-5 lg:px-8"><p className="text-xs font-bold uppercase tracking-[.2em] gold">The Learnora loop</p><h2 className="mt-4 max-w-3xl font-display text-5xl sm:text-6xl">Learning should leave a <span className="gold">trace.</span></h2><p className="mt-5 max-w-2xl leading-7 text-slate-400">Each stage should help you move from understanding an idea to using it, reflecting on it and keeping a record of the work.</p><div className="mt-12 grid gap-5 md:grid-cols-2">{items.map(([n,t,d,img,I,href]:any)=><motion.a whileHover={{y:-5}} href={href} key={t} className="group relative min-h-[360px] overflow-hidden rounded-[2rem] border border-white/[.08]"><div className="story absolute inset-0 opacity-55" style={{backgroundImage:"linear-gradient(180deg,#07090c00 0%,#07090c 95%),url("+img+")"}}/><div className="relative flex min-h-[360px] flex-col justify-between p-7"><span className="text-sm gold">{n}</span><div><I className="mb-5 gold" size={22}/><h3 className="font-display text-4xl">{t}</h3><p className="mt-3 max-w-md text-sm leading-6 text-slate-300">{d}</p><span className="mt-5 inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-[.15em] gold">Explore this stage <span aria-hidden="true">↗</span></span></div></div></motion.a>)}</div></div></section>}