"use client";
import { useEffect, useState } from "react";
import { ArrowRight, Building2, Search } from "lucide-react";
import PublicNav from "../../components/public/PublicNav";
import PublicFooter from "../../components/public/PublicFooter";
import EmptyState from "../../components/feedback/EmptyState";
import { publicOrganisations } from "../../lib/api/public";

export default function OrganisationsPage() {
  const [items,setItems]=useState<any[]>([]);
  const [loading,setLoading]=useState(true);
  const [error,setError]=useState("");
  const [query,setQuery]=useState("");
  useEffect(()=>{publicOrganisations().then(r=>setItems(r.organisations||[])).catch(e=>setError(e.message||"Organisations could not be loaded.")).finally(()=>setLoading(false));},[]);
  const filtered=items.filter(o=>[o.name,o.description,o.organisation_type].filter(Boolean).join(" ").toLowerCase().includes(query.toLowerCase()));
  const usedLogos=new Set<string>();
  return <><PublicNav/><main className="mx-auto max-w-[82rem] px-5 pb-24 pt-36 lg:px-8">
    <div className="grid gap-10 lg:grid-cols-[1fr_.65fr] lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[.22em] gold">Learnora network</p><h1 className="mt-5 max-w-3xl font-display text-5xl leading-tight sm:text-6xl">Discover organisations building learning into their work.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-400">This directory only includes active organisations that have explicitly opted into public discovery. Private customer workspaces remain private.</p></div><div className="border border-white/[.12] bg-[#11171e] p-6"><Building2 className="gold" size={24}/><p className="mt-4 font-semibold">Different organisations, different needs</p><p className="mt-2 text-sm leading-6 text-slate-500">Schools, academies, teams and businesses can configure learning around their own structure and priorities.</p><a href="/get-started" className="mt-5 inline-flex items-center gap-2 text-sm font-semibold gold">Work with Learnora <ArrowRight size={15}/></a></div></div>
    <div className="mt-12 flex max-w-xl items-center gap-3 rounded-xl border border-white/10 bg-[#0e1319] px-4"><Search className="text-slate-500" size={18}/><input aria-label="Search organisations" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search organisations or type" className="w-full bg-transparent py-4 text-sm outline-none placeholder:text-slate-600"/></div>
    <div className="mt-10">{loading?<div className="rounded-2xl border border-white/10 p-8 text-sm text-slate-500">Loading public organisations…</div>:error?<EmptyState title="Organisation directory unavailable" message={error}/>:filtered.length?<div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{filtered.map((o,i)=>{const candidate=typeof o.logo_url==="string"?o.logo_url.trim():"";const key=candidate?candidate.split("?")[0]:"";const logo=key&&!usedLogos.has(key)?candidate:"";if(logo)usedLogos.add(key);return <article key={o.id} className="border border-white/[.12] bg-[#11171e] p-6 transition-colors hover:border-white/[.2]"><div className="flex h-14 w-14 items-center justify-center overflow-hidden border border-white/[.1] bg-white/[.025]">{logo?<img src={logo} alt="" loading="lazy" className="h-full w-full object-contain"/>:<span className="font-display text-2xl text-[var(--gold-light)]">{String(o.name||"O").trim().charAt(0).toUpperCase()}</span>}</div><p className="mt-5 text-[10px] font-semibold uppercase tracking-[.16em] text-slate-500">{(o.organisation_type||"Organisation").replaceAll("_"," ")}</p><h2 className="mt-2 text-xl font-semibold">{o.name}</h2><p className="mt-3 min-h-12 text-sm leading-6 text-slate-400">{o.description||"An organisation using Learnora for learning and capability development."}</p></article>})}</div>:<EmptyState title={query?"No organisations match that search":"No public organisations listed yet"} message={query?"Try another name or organisation type.":"Organisations appear here only after they opt into public discovery. You can enquire about creating a private, branded Learnora workspace."}/>}</div>
    <div className="mt-12 border border-white/[.12] border-l-2 border-l-[var(--gold)] bg-[#11171e] p-8 sm:p-10"><p className="text-xs font-bold uppercase tracking-[.22em] gold">For your organisation</p><h2 className="mt-4 max-w-2xl font-display text-3xl sm:text-4xl">Build a learning workspace around the way your people work.</h2><p className="mt-4 max-w-2xl leading-7 text-slate-400">Tell us about your organisation, the people you want to support and the outcomes you want learning to contribute to.</p><a href="/get-started" className="mt-7 inline-flex items-center gap-2 rounded-xl bg-[#d7ad35] px-5 py-3.5 font-bold text-black">Start an enquiry <ArrowRight size={16}/></a></div>
  </main><PublicFooter/></>;
}
