const API_URL=(process.env.NEXT_PUBLIC_API_URL||"").replace(/\/$/,"");
export function token(){if(typeof window==="undefined")return "";return localStorage.getItem("phx_token")||""}
export function saveToken(v:string){localStorage.setItem("phx_token",v)}
export function logout(){localStorage.removeItem("phx_token")}
export async function api<T=any>(path:string,init:RequestInit={}):Promise<T>{const h=new Headers(init.headers);h.set("Content-Type","application/json");const t=token();if(t)h.set("Authorization","Bearer "+t);const target=API_URL+(path[0]==="/"?"":"/")+path;const r=await fetch(target,{...init,headers:h,cache:"no-store"});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(typeof b.detail==="string"?b.detail:typeof b.error==="string"?b.error:"The request could not be completed.");return b}
const p=(x:string)=>"/backend-api"+x;
export const login=(email:string,password:string)=>api(p("/auth/login"),{method:"POST",body:JSON.stringify({email,password})});
export const register=(name:string,email:string,password:string)=>api(p("/auth/register"),{method:"POST",body:JSON.stringify({name,email,password})});
export const me=()=>api(p("/auth/me"));export const forgot=(email:string)=>api(p("/auth/forgot-password"),{method:"POST",body:JSON.stringify({email})});
export const reset=(token:string,new_password:string,confirm_password:string)=>api(p("/auth/reset-password"),{method:"POST",body:JSON.stringify({token,new_password,confirm_password})});
export const verify=(token:string)=>api(p("/auth/verify-email"),{method:"POST",body:JSON.stringify({token})});
export const getCourses=()=>api(p("/courses?status=published"));export const getCourse=(id:string)=>api(p("/courses/"+encodeURIComponent(id)));export const getStructure=(id:string)=>api(p("/course-content/courses/"+encodeURIComponent(id)+"/structure"));
export const getProgress=()=>api(p("/progress/me"));export const getEvidence=()=>api(p("/evidence/me"));export const askAI=(message:string)=>api(p("/ai/ask"),{method:"POST",body:JSON.stringify({feature:"tutor",message})});
export const getAIUsage=()=>api(p("/ai/usage"));export const adminStats=()=>api(p("/admin/stats"));export const adminUsers=()=>api(p("/admin/users"));export const adminAdmins=()=>api(p("/admin/admins"));export const adminActivity=()=>api(p("/admin/activity"));export const adminSecurity=()=>api(p("/admin/security-summary"));export const getOrgs=()=>api(p("/organisations"));export const creatorMe=()=>api(p("/creator/me"));export const creatorEarnings=()=>api(p("/creator/earnings"));export const creatorPayouts=()=>api(p("/creator-finance/payouts"));