"use client";

import { useEffect,useMemo,useState } from "react";
import { ArrowUpRight, BookOpen, Clock3, Layers3, Search, SlidersHorizontal } from "lucide-react";
import Shell from "../../components/Shell";
import EmptyState from "../../components/EmptyState";
import { teamMe } from "../../lib/api";
import { contentCourses,courseStructure } from "../../lib/content";

export default function CourseLibrary() {
  const [user,setUser]=useState<any>(null),[items,setItems]=useState<any[]>([]),[summaries,setSummaries]=useState<Record<string,any>>({}),[query,setQuery]=useState(""),[status,setStatus]=useState("all"),[loading,setLoading]=useState(true),[error,setError]=useState("");
  useEffect(()=>{let active=true;Promise.all([teamMe(),contentCourses()]).then(async([me,result])=>{if(!active)return;setUser(me);const courses=result.courses||[];setItems(courses);const pairs=await Promise.all(courses.map(async(c:any)=>{try{return [String(c.id),await courseStructure(String(c.id))] as const}catch{return [String(c.id),null] as const}}));if(active)setSummaries(Object.fromEntries(pairs.filter((x:any)=>x[1])))}).catch(e=>{if(active)setError(e.message||"Course library could not be loaded.")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
  const filtered=useMemo(()=>items.filter(c=>{const text=[c.title,c.slug,c.description,c.short_description,c.level].filter(Boolean).join(" ").toLowerCase();return text.includes(query.trim().toLowerCase())&&(status==="all"||String(c.status||"draft")===status)}),[items,query,status]);
  if(!user&&!loading)return <div className="p-8 text-sm text-slate-500">Workspace unavailable.</div>;
  return <Shell roles={user?.roles||[]} active="courses">
    <section className="border-b border-white/[.1] pb-7">
      <p className="section-kicker">Learning operations / Library</p>
      <div className="mt-3 flex flex-wrap items-end justify-between gap-5"><div><h1 className="font-display text-4xl tracking-tight sm:text-5xl">Course library</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-slate-400">Review live course records, publication state and curriculum health. Course counts come from the backend, not sample data.</p></div><a href="/content" className="inline-flex min-h-11 items-center gap-2 rounded-lg bg-[var(--gold)] px-4 text-sm font-bold text-[#17140d] hover:bg-[var(--gold2)]">Manage curriculum <ArrowUpRight size={15}/></a></div>
    </section>
    <section className="mt-6 grid gap-3 sm:grid-cols-3">
      {[{label:"Total courses",value:items.length,icon:BookOpen},{label:"Published",value:items.filter(c=>c.status==="published").length,icon:Layers3},{label:"Draft / other",value:items.filter(c=>c.status!=="published").length,icon:Clock3}].map(({label,value,icon:Icon})=><div key={label} className="border border-white/[.1] bg-[#11171e] p-4"><div className="flex items-center justify-between text-xs text-slate-500"><span>{label}</span><Icon size={16} className="text-[var(--gold2)]"/></div><p className="mt-3 text-3xl font-semibold tabular-nums">{loading?"—":value}</p></div>)}
    </section>
    <section className="mt-7" aria-label="Search and filter courses">
      <div className="grid gap-3 md:grid-cols-[1fr_13rem_auto]">
        <label className="flex min-h-12 items-center gap-3 border border-white/[.12] bg-[#11171e] px-4 focus-within:border-[var(--gold)]"><Search size={16} className="text-slate-500"/><input value={query} onChange={e=>setQuery(e.target.value)} aria-label="Search courses" placeholder="Search course name, slug or description" className="w-full bg-transparent text-sm outline-none placeholder:text-slate-600"/></label>
        <label className="flex min-h-12 items-center gap-3 border border-white/[.12] bg-[#11171e] px-4"><SlidersHorizontal size={15} className="text-slate-500"/><select value={status} onChange={e=>setStatus(e.target.value)} aria-label="Filter by status" className="w-full bg-transparent text-sm outline-none"><option value="all">All statuses</option><option value="published">Published</option><option value="draft">Draft</option><option value="archived">Archived</option></select></label>
        <div className="flex items-center px-1 text-xs tabular-nums text-slate-500">{loading?"Loading…":filtered.length+" of "+items.length+" courses"}</div>
      </div>
    </section>
    <section className="mt-5" aria-live="polite">
      {error?<div role="alert" className="border border-red-300/20 bg-red-300/[.04] p-5 text-sm text-red-200">{error}</div>:loading?<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{[1,2,3].map(i=><div key={i} className="h-56 animate-pulse border border-white/[.08] bg-[#11171e] motion-reduce:animate-none"/>)}</div>:filtered.length?<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{filtered.map((c:any,i:number)=>{const summary=summaries[String(c.id)];return <article key={c.id} className="flex min-w-0 flex-col border border-white/[.1] bg-[#11171e] transition-colors hover:border-white/[.2]"><div className="flex items-start justify-between gap-4 border-b border-white/[.08] p-5"><div className="min-w-0"><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-[var(--gold2)]">Course / {String(i+1).padStart(2,"0")}</p><h2 className="mt-3 break-words font-display text-2xl leading-tight">{c.title||"Untitled course"}</h2><p className="mt-2 break-all text-[11px] text-slate-600">{c.slug||"No slug"}</p></div><span className={"shrink-0 border px-2 py-1 text-[9px] font-semibold uppercase tracking-[.12em] "+(c.status==="published"?"border-emerald-300/20 text-emerald-200":"border-white/[.12] text-slate-400")}>{c.status||"draft"}</span></div><div className="flex-1 p-5"><p className="min-h-[4.5rem] text-sm leading-6 text-slate-400">{c.short_description||c.description||"No course description has been added."}</p><div className="mt-5 grid grid-cols-2 gap-2"><div className="border border-white/[.08] p-3"><p className="text-[10px] uppercase tracking-[.12em] text-slate-600">Modules</p><p className="mt-1 text-xl font-semibold tabular-nums">{summary?.module_count??"—"}</p></div><div className="border border-white/[.08] p-3"><p className="text-[10px] uppercase tracking-[.12em] text-slate-600">Lessons</p><p className="mt-1 text-xl font-semibold tabular-nums">{summary?.lesson_count??"—"}</p></div></div></div><div className="flex items-center justify-between gap-3 border-t border-white/[.08] p-4"><span className="text-xs text-slate-600">{c.level||"Level not set"}</span><a href={"/content?course="+encodeURIComponent(c.id)} className="inline-flex min-h-9 items-center gap-2 border border-white/[.14] px-3 text-xs font-semibold text-slate-200 transition-colors hover:border-[var(--gold)] hover:text-[var(--gold2)]">Manage course <ArrowUpRight size={14}/></a></div></article>})}</div>:<EmptyState title={query||status!=="all"?"No courses match your filters":"No courses found"} message={query||status!=="all"?"Change your search or status filter to see more courses.":"No course records were returned by the backend. Create a course when you are ready to add real content."}/>}
    </section>
  </Shell>;
}
