"use client";
import { useEffect,useState } from "react";
import { ArrowRight,CheckCircle2,Clock3,FileCheck2,LockKeyhole,RefreshCw,ShieldCheck } from "lucide-react";
import { request } from "../../lib/api/client";
import Logo from "../../components/brand/Logo";
import Toast from "../../components/feedback/Toast";
const stages=[["submitted","Request submitted"],["under_review","Learnora review"],["discussion","Discussion"],["contract_preparation","Contract preparation"],["contract_sent","Contract sent"],["pending_approval","Awaiting Learnora approval"],["active","Workspace active"]];
const label=(s:string)=>s.replaceAll("_"," ").replace(/^./,x=>x.toUpperCase());
export default function OrganisationPortal(){
 const [data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[busy,setBusy]=useState(false),[name,setName]=useState(""),[title,setTitle]=useState(""),[ack,setAck]=useState(false),[notice,setNotice]=useState("");
 async function load(){setLoading(true);setError("");try{const r=await request<any>("/commercial/portal/me");setData(r);setName(r.request?.contact_name||"");}catch(e:any){location.href="/login";}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function sign(e:any){e.preventDefault();if(!data?.contract?.id||!ack||!name.trim())return;setBusy(true);setError("");try{const r=await request<any>("/commercial/portal/contracts/"+encodeURIComponent(data.contract.id)+"/sign",{method:"POST",body:JSON.stringify({signer_name:name,signer_title:title,acknowledgement:ack})});setNotice("Signature acknowledgement recorded. Learnora must still explicitly approve the contract.");setData((old:any)=>({...old,request:{...old.request,status:r.request_status},contract:r.contract}));}catch(e:any){setError(e.message||"The contract acknowledgement could not be saved.");}finally{setBusy(false)}}
 const req=data?.request,contract=data?.contract,version=data?.contract_version;
 const current=stages.findIndex(([key])=>key===req?.status);
 return <div className="min-h-screen bg-[#07090c] text-white"><header className="border-b border-white/[.07]"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 lg:px-8"><a href="/"><Logo/></a><span className="flex items-center gap-2 text-xs text-slate-500"><LockKeyhole size={14}/> Organisation onboarding portal</span></div></header>
 <main className="mx-auto max-w-7xl px-5 py-10 sm:py-14 lg:px-8">{loading?<div className="grid min-h-[50vh] place-items-center"><div className="text-center"><RefreshCw className="mx-auto animate-spin gold" size={28}/><p className="mt-4 text-sm text-slate-500">Loading your onboarding workspace…</p></div></div>:req?<div className="grid gap-8 xl:grid-cols-[.72fr_1.28fr]">
 <aside className="space-y-5"><section className="rounded-[1.7rem] border border-white/[.08] bg-[#0e1319] p-6"><p className="text-xs font-bold uppercase tracking-[.2em] gold">Your request</p><h1 className="mt-4 font-display text-3xl sm:text-4xl">{req.organisation_name}</h1><p className="mt-3 text-sm leading-6 text-slate-400">This portal keeps your enquiry, contract and next steps together. Commercial conversations may happen outside Learnora; return here for formal updates.</p><div className="mt-6 rounded-xl border border-white/[.07] bg-black/20 p-4"><p className="text-xs text-slate-500">Request reference</p><p className="mt-1 break-all font-mono text-sm">{req.id}</p><p className="mt-4 text-xs text-slate-500">Current status</p><p className="mt-1 font-semibold text-[#f2d477]">{label(req.status||"submitted")}</p></div></section>
 <section className="rounded-2xl border border-white/[.08] bg-[#0e1319] p-6"><h2 className="font-semibold">Onboarding progress</h2><div className="mt-5 space-y-4">{stages.map(([key,text],i)=>{const done=current>i,active=current===i;return <div key={key} className="flex gap-3"><div className={"grid h-7 w-7 shrink-0 place-items-center rounded-full border "+(done?"border-emerald-300/30 bg-emerald-300/10 text-emerald-200":active?"border-[#d7ad35]/50 bg-[#d7ad35]/10 gold":"border-white/10 text-slate-600")}>{done?<CheckCircle2 size={15}/>:<span className="text-[10px]">{i+1}</span>}</div><p className={"pt-1 text-sm "+(active?"font-semibold text-white":done?"text-slate-300":"text-slate-500")}>{text}</p></div>})}</div>{["declined","closed"].includes(req.status)&&<p className="mt-5 rounded-xl border border-amber-300/10 bg-amber-300/[.04] p-3 text-xs leading-5 text-amber-100/70">This request is closed and is not an active workspace.</p>}</section></aside>
 <section className="space-y-5"><div className="rounded-[1.7rem] border border-white/[.08] bg-[#0e1319] p-6 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.2em] gold">Contract and next steps</p><h2 className="mt-3 font-display text-3xl">Organisation onboarding</h2></div><button onClick={()=>void load()} className="inline-flex items-center gap-2 rounded-xl border border-white/10 px-3 py-2 text-xs text-slate-400 hover:text-white"><RefreshCw size={14}/> Refresh</button></div>
 {!contract?<div className="mt-8 rounded-2xl border border-dashed border-white/10 p-8 text-center"><FileCheck2 className="mx-auto text-slate-600" size={25}/><h3 className="mt-4 font-semibold">No contract has been sent yet</h3><p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-slate-500">Learnora will review the request and prepare a contract. When it is formally sent, it will appear here for you to review and acknowledge.</p></div>:<div className="mt-7 space-y-5"><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-white/[.07] bg-black/20 p-4"><p className="text-xs text-slate-500">Contract reference</p><p className="mt-2 text-sm font-semibold">{contract.contract_number}</p></div><div className="rounded-xl border border-white/[.07] bg-black/20 p-4"><p className="text-xs text-slate-500">Status</p><p className="mt-2 text-sm font-semibold text-[#f2d477]">{label(contract.status)}</p></div><div className="rounded-xl border border-white/[.07] bg-black/20 p-4"><p className="text-xs text-slate-500">Contract term</p><p className="mt-2 text-sm font-semibold">{contract.start_date||"To be confirmed"} – {contract.end_date||"To be confirmed"}</p></div></div>
 {contract.document_url&&<a href={contract.document_url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-sm font-semibold gold">Open contract document <ArrowRight size={15}/></a>}
 {version?.draft_content?<div className="rounded-2xl border border-white/[.07] bg-black/20 p-5 sm:p-6"><div className="flex items-center justify-between gap-3"><h3 className="font-semibold">Contract text</h3><span className="text-xs text-slate-600">Version {version.version_number}</span></div><article className="mt-4 max-h-[480px] overflow-y-auto whitespace-pre-wrap text-sm leading-7 text-slate-300">{version.draft_content}</article></div>:<p className="rounded-xl border border-amber-300/10 bg-amber-300/[.04] p-4 text-sm text-amber-100/70">Contract text is not available in this response. Please contact Learnora before signing.</p>}
 {contract.status==="sent"&&version?.review_status==="approved"&&<form onSubmit={sign} className="rounded-2xl border border-[#d7ad35]/20 bg-[#d7ad35]/[.04] p-5 sm:p-6"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 shrink-0 gold" size={21}/><div><h3 className="font-semibold">Review and sign</h3><p className="mt-2 text-sm leading-6 text-slate-400">This records a typed-name electronic acknowledgement and timestamp. Read the full contract above and obtain independent legal advice where appropriate.</p></div></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm text-slate-300">Signer full name<input value={name} onChange={e=>setName(e.target.value)} required minLength={2} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 p-3 outline-none focus:border-[#d7ad35]/50"/></label><label className="text-sm text-slate-300">Title / authority<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Director" className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 p-3 outline-none focus:border-[#d7ad35]/50"/></label></div><label className="mt-5 flex items-start gap-3 text-sm leading-6 text-slate-300"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)} className="mt-1 accent-[#d7ad35]"/><span>I confirm that I am authorised to sign for this organisation, have reviewed the contract displayed above, and intend my typed name to be recorded as the organisation's electronic signature acknowledgement.</span></label><button disabled={busy||!ack||!name.trim()||!version?.draft_content} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-[#d7ad35] px-5 py-3.5 text-sm font-bold text-black disabled:opacity-50">{busy?"Recording signature…":"Sign and submit for approval"}<ArrowRight size={15}/></button></form>}
 {contract.status==="signed"&&<div className="rounded-xl border border-emerald-300/20 bg-emerald-300/[.05] p-4"><p className="font-semibold text-emerald-200">Signature acknowledgement recorded</p><p className="mt-2 text-sm leading-6 text-slate-400">Signed by {contract.signature_name||"the named representative"}{contract.signature_title?", "+contract.signature_title:""} on {contract.signed_at?new Date(contract.signed_at).toLocaleString():"the recorded signing date"}. Learnora must still approve before activation.</p></div>}
 {contract.status==="active"&&<div className="rounded-xl border border-emerald-300/20 bg-emerald-300/[.05] p-5"><p className="font-semibold text-emerald-200">Your contract is active</p><p className="mt-2 text-sm leading-6 text-slate-400">Learnora has activated the organisation workspace. Sign in again to enter it.</p><a href="/login" className="mt-4 inline-flex items-center gap-2 rounded-xl bg-[#d7ad35] px-4 py-3 text-sm font-bold text-black">Sign in to workspace <ArrowRight size={15}/></a></div>}
 </div>}</div><div className="rounded-2xl border border-white/[.06] bg-white/[.015] p-5"><div className="flex items-start gap-3"><Clock3 className="mt-0.5 shrink-0 text-slate-500" size={17}/><p className="text-xs leading-6 text-slate-500">Signing does not activate access. Learnora records a separate approval decision, then explicitly activates the workspace. Request, contract and workspace states remain distinct.</p></div></div></section></div>:<div className="rounded-2xl border border-white/10 p-8"><h1 className="text-xl font-semibold">Portal unavailable</h1><p className="mt-2 text-sm text-slate-500">{error||"No organisation request is linked to this account."}</p><button onClick={()=>void load()} className="mt-5 rounded-xl border border-white/10 px-4 py-2.5 text-sm">Try again</button></div>}
 {notice&&<div role="status" className="fixed bottom-5 right-5 z-50 max-w-lg rounded-xl border border-emerald-300/20 bg-[#101b15] p-4 text-sm text-emerald-100">{notice}</div>}{error&&<Toast title="Portal action failed" message={error} type="error" onClose={()=>setError("")}/>}
 </main></div>;
}
