import Logo from "../../components/brand/Logo";
const sections=[
["1. About these terms","These Terms of Use apply when you access or use Learnora ME, including accounts, courses, practice tools, AI features, portfolios, creator tools and organisation workspaces. Learnora's legal entity and formal notice details will be added by the platform owner before public launch."],
["2. Your account","Provide accurate information, keep your credentials confidential and promptly update material changes. You are responsible for activity through your account except where applicable law provides otherwise. Do not impersonate another person, share access in a way that compromises security, or attempt to bypass access controls."],
["3. Learning access and organisations","Course and feature access depends on the applicable free, trial, paid, scholarship, promotional or organisation entitlement. Access can differ by course, cohort, organisation or plan. Organisation administrators may manage memberships and access in line with their programme. Leaving an organisation or the end of its contract may affect access to organisation-provided content."],
["4. Trials, subscriptions and payments","Where offered, trial duration, price, renewal date, billing interval, cancellation process and included features should be shown before you commit. Paid subscriptions may renew according to the checkout terms until cancelled. Cancellation generally affects future renewal and does not automatically reverse a completed charge, except where required by law or the applicable offer. Do not rely on a trial or price unless it is displayed in your account or checkout."],
["5. Learning content and intellectual property","Learnora and its licensors retain rights in the platform, branding and content they own. Instructors, organisations and creators may retain rights in their own materials. You receive a limited, personal or programme-specific right to use content made available to you; you must not redistribute, resell, publicly upload, scrape or commercially exploit content without permission. You retain rights you have in your own submissions, subject to the permissions needed to operate features you choose to use."],
["6. User submissions and conduct","You must not upload unlawful, infringing, deceptive, abusive, malicious or confidential material you are not authorised to share. Do not use Learnora to harass others, compromise systems, manipulate assessments, misrepresent qualifications, or interfere with other users. You are responsible for ensuring you have permission to submit third-party information or materials."],
["7. AI-assisted features","AI-generated explanations, summaries, feedback, questions and suggestions may be incomplete, inaccurate, outdated or biased. Review outputs before relying on them. AI features support learning and do not guarantee a grade, qualification, job, income, certification or professional outcome. Do not submit highly sensitive or confidential information unless the relevant feature expressly supports it and you are authorised to do so."],
["8. Instructor and creator features","Instructor or creator access may require application, verification, review or separate terms. Approval is not guaranteed. Where earnings, fees, refunds, tax documentation or payouts apply, the relevant creator or commercial terms will govern those details. Do not claim that a course or credential is accredited unless that claim is expressly authorised and accurate."],
["9. Availability, suspension and termination","We may maintain, update or discontinue features and may restrict or suspend access where reasonably necessary for security, suspected abuse, non-payment, legal compliance or breach of these terms. Where practical and appropriate, we will provide notice and a route to resolve the issue. Nothing in these terms removes rights that cannot lawfully be excluded."],
["10. Disclaimers and liability","Learnora is provided on an availability basis, subject to applicable law. We do not guarantee uninterrupted access or specific educational, commercial or career outcomes. Nothing in these terms excludes liability or rights that cannot be excluded under applicable law. Any legally permitted limitation of liability must be finalised by the platform owner with qualified counsel before launch."],
["11. Privacy","Our handling of personal data is described in the Privacy Policy. By using a feature, you should review the notice relevant to that feature. The Privacy Policy explains the types of data processed, purposes, sharing, retention and choices."],
["12. Changes and governing law","We may update these terms as the service evolves. Material changes will be communicated where required. Governing law, dispute venue, formal notice address and legal entity details are intentionally left for the platform owner to complete and have reviewed before launch."],
];
export default function TermsPage(){return <main className="min-h-screen bg-[#07090c] px-5 py-10 text-white"><div className="mx-auto max-w-4xl"><a href="/"><Logo/></a><p className="mt-12 text-xs uppercase tracking-[.25em] text-[#d7ad35]">Legal · Terms</p><h1 className="mt-3 font-display text-5xl">Terms of Use</h1><p className="mt-4 text-sm text-slate-500">Effective date: 10 October 2026 · Draft for operational review</p><p className="mt-8 rounded-xl border border-[#d7ad35]/20 bg-[#d7ad35]/[.05] p-4 text-sm leading-6 text-slate-300">This is a product-specific working draft, not legal advice. Complete commercial, legal-entity and contact details and obtain qualified review before relying on these terms for public launch.</p><div className="mt-10 space-y-8">{sections.map(([title,body])=><section key={title}><h2 className="text-xl font-semibold">{title}</h2><p className="mt-3 leading-7 text-slate-400">{body}</p></section>)}</div><p className="mt-12 border-t border-white/10 pt-6 text-xs text-slate-600">Learnora ME · Terms of Use</p><a href="/privacy" className="mt-4 inline-block text-sm text-[#f2d477]">Read Privacy Policy →</a></div></main>
}
